'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
for(const name of ['core','geometry','vias','font','platforms','maker-parts','carriers','modules','block-catalog','blocks','router','planes','casebench-export'])require('../src/'+name+'.js');
const C=globalThis.CB,X=C.CaseBench,results=[];
const out=path.join(__dirname,'output');fs.mkdirSync(out,{recursive:true});
function test(name,fn){try{fn();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.stack});console.error('FAIL',name,e.stack);process.exitCode=1;}}
function same(d,fn){const before=JSON.stringify(d);let r;try{r=fn();}finally{assert.equal(JSON.stringify(d),before,'Export mutated the source');}return r;}
function body(){const d=C.example('mixed');d.parts[0].rotation=37;d.parts[0].side='bottom';return d;}
function placed(d,lib,x=30,y=25){const p=C.makePart(d,lib,x,y);d.parts.push(p);return p;}
function assertGeometry(source,target){for(const k of ['board','parts','holes','cutouts','vias','keepouts','traces','nets','zones','blockInstances'])assert.deepEqual(target[k],source[k],k);assert.deepEqual(C.pads(target),C.pads(source));assert.deepEqual(C.G.holes(target),C.G.holes(source));}

test('Native CopperBench schema 5 with explicit mm; no new mechanical wrapper',()=>{const d=C.example(),r=X.prepare(d);assert.equal(r.document.app,'COPPERBENCH');assert.equal(r.document.schema,5);assert.equal(r.document.units,'mm');assert.equal(r.document.id,d.id);assert.equal(JSON.parse(r.json).id,d.id);assert.equal(r.document.components,undefined);});
test('Source document, dates and editable geometry are not mutated',()=>{const d=body(),r=same(d,()=>X.prepare(d));assertGeometry(d,r.document);assert.equal(r.document.updated,d.updated);assert.equal(r.document.created,d.created);});
test('Filename is JSON, useful, bounded and safe for paths',()=>{assert.equal(X.filename('Sensor board rev A'),'Sensor-board-rev-A-casebench.json');for(const title of ['../../board/CON<>:"|?*','', '😀', 'x'.repeat(500)]){const name=X.filename(title);assert.match(name,/^[a-zA-Z0-9_-]+-casebench\.json$/);assert(name.length<=95);}});
test('Every supported outline remains native rather than flattened',()=>{for(const shape of ['rect','rounded','circle','polygon']){const d=C.blank();d.board.shape=shape;if(shape==='polygon')d.board.points=[{x:-2,y:3},{x:48,y:3},{x:45,y:32},{x:2,y:28}];const r=X.prepare(d);assert.deepEqual(r.document.board,d.board);assert.deepEqual(C.G.outline(r.document),C.G.outline(d));}});
test('Custom outline summary uses actual extents without shifting its origin',()=>{const d=C.blank();d.board.shape='polygon';d.board.points=[{x:-10,y:12},{x:30,y:12},{x:30,y:32},{x:-10,y:32}];const r=X.prepare(d);assert.equal(r.summary.width,40);assert.equal(r.summary.height,20);assert.equal(r.document.board.points[0].x,-10);});
test('Bottom parts keep local pads: mirror X then rotate exactly once',()=>{const d=body(),before=C.pads(d),r=X.prepare(d);assert.deepEqual(C.pads(r.document),before);assert.deepEqual(r.document.parts[0].pads,d.parts[0].pads);assert.equal(r.document.parts[0].rotation,37);assert.equal(r.document.parts[0].side,'bottom');});
test('Active linked mounting holes are retained locally and never duplicated at root',()=>{const f=C.LIB.find(p=>p.module),d=C.Modules?C.Modules.template(f.id,true):C.blank();if(!d.parts.length){const p=placed(d,f);p.mountingHoles=C.clone(p.module.holePattern);}const p=d.parts[0];p.rotation=90;p.side='bottom';const r=X.prepare(d);assert.equal(r.document.holes.length,d.holes.length);assert.deepEqual(C.mountingHoles(r.document),C.mountingHoles(d));assert.equal(r.summary.linkedMountingHoles,p.mountingHoles.length);});
test('Disabled module mounting pattern is reference-only, not a set of new bores',()=>{const d=C.blank();const p=placed(d,C.LIB.find(p=>p.module));p.mountingHoles=[];const r=X.prepare(d);assert.equal(r.summary.mountingHoles,0);assert.deepEqual(r.document.parts[0].module.holePattern,p.module.holePattern);});
test('Module envelope height is not increased by stack gap a second time',()=>{const d=C.blank(),p=placed(d,C.LIB.find(p=>p.module));p.module.showBody=false;const r=X.prepare(d);assert.equal(r.document.parts[0].body.z,p.body.z);assert.equal(r.document.parts[0].module.stackGap,p.module.stackGap);assert.equal(r.document.parts[0].module.showBody,false);assert.equal(r.summary.topEnvelopeHeight,p.body.z);});
test('Carrier and platform references and attached keepouts survive export',()=>{for(const f of C.LIB.filter(p=>p.carrier||p.platform)){const d=C.blank();placed(d,f);const r=X.prepare(d);assert.deepEqual(r.document.parts,d.parts);assert.deepEqual(C.keepouts(r.document),C.keepouts(d));}});
test('Every library variant exports its embedded footprint without catalog substitution',()=>{assert.equal(C.LIB.length,193);for(const f of C.LIB){const d=C.blank();placed(d,f);const r=X.prepare(d);assert.deepEqual(r.document.parts,d.parts,f.id);}});
test('Board slots, plated pad slots and vias retain their dimensions and identities',()=>{const d=C.blank(),p=placed(d,'header2');p.pads[0].slot=1.2;p.pads[0].rotation=20;p.rotation=27;p.side='bottom';d.holes.push({id:'slot-npth',x:8,y:8,drill:2,slot:5,rotation:65,plated:false});d.vias.push({id:'v1',x:15,y:15,diameter:1,drill:.4,net:null});const r=X.prepare(d);assertGeometry(d,r.document);assert.equal(r.summary.slots,2);assert.equal(r.summary.platedDrills,3);assert.equal(r.summary.mountingHoles,1);});
test('Cutouts are kept as independent native polygons',()=>{const d=C.blank();d.cutouts.push({id:'cut1',points:C.G.rect(25,25,10,8)});const r=X.prepare(d);assert.deepEqual(r.document.cutouts,d.cutouts);assert.equal(r.summary.cutouts,1);});
test('Copper design errors and unrouted nets do not block a mechanical handoff',()=>{const d=C.example();assert(C.G.connectivity(d).unrouted>0);assert(X.prepare(d).json);});
test('Unfilled planes are preserved and do not block enclosure export',()=>{const d=C.example();C.Planes.set(d,'bottom',d.nets[0].id);assert(!d.zones[0].fill);const r=X.prepare(d);assert.deepEqual(r.document.zones,d.zones);});
test('Board-only handoff omits artwork, images, baseline and unused library',()=>{const d=C.example();d.assets=[{id:'image',data:'data:image/png;base64,AAAA'}];d.baseline={time:'2026-09-18',document:C.snapshot(C.example())};d.blockLibrary=[C.clone(C.BLOCK_CATALOG[0])];const r=same(d,()=>X.prepare(d));assert.equal(r.document.art.length,0);assert.equal(r.document.assets.length,0);assert.equal(r.document.blockLibrary.length,0);assert.equal(r.document.baseline,null);assertGeometry(d,r.document);});
test('Project extras option retains the complete project data',()=>{const d=C.example();d.assets=[{id:'image',data:'data:image/png;base64,AAAA'}];d.baseline={time:'2026-09-18',document:C.snapshot(C.example())};const r=same(d,()=>X.prepare(d,{includeProjectData:true}));assert.deepEqual(r.document.art,d.art);assert.deepEqual(r.document.assets,d.assets);assert.deepEqual(r.document.baseline,d.baseline);assert(r.summary.complete);});
test('Export reopens in CopperBench as native schema 5',()=>{const r=X.prepare(body());assertGeometry(r.document,C.validateDoc(JSON.parse(r.json)));});
test('Future native schema is rejected, not relabelled as 5',()=>{const d=C.blank();d.schema=6;assert.throws(()=>same(d,()=>X.prepare(d)),/schema|newer|version/i);});
test('Wrong units and non-project JSON fail with actionable errors',()=>{const d=C.blank();d.units='in';assert.throws(()=>X.prepare(d),/millimetres/);assert.throws(()=>X.prepare({app:'CASEBENCH'}),/CopperBench/);assert.throws(()=>X.prepare(C.blank(),{includeProjectData:'yes'}),/option/);});
test('Blank board works and reports that component envelopes are absent',()=>{const r=X.prepare(C.blank());assert.equal(r.summary.components,0);assert(r.warnings.some(s=>s.includes('Bare board')));});
test('Self-intersecting board and cutout boundaries fail safely',()=>{const d=C.blank();d.board.shape='polygon';d.board.points=[{x:0,y:0},{x:30,y:30},{x:0,y:30},{x:30,y:0}];assert.throws(()=>same(d,()=>X.prepare(d)),/boundary/);const b=C.blank();b.cutouts=[{id:'bad',points:d.board.points}];assert.throws(()=>X.prepare(b),/Cutout/);});
test('Out-of-board parts warn but are not moved or silently dropped',()=>{const d=C.blank();placed(d,'r-axial',-25,-25);const r=X.prepare(d);assert.equal(r.document.parts.length,1);assert.equal(r.document.parts[0].x,-25);assert(r.warnings.length);});
test('CaseBench native adapter component limit is preflighted',()=>{const d=C.blank();for(let i=0;i<513;i++)placed(d,'testpoint');assert.throws(()=>X.prepare(d),/Placed components.*513 \/ 512/);});
test('CaseBench polygon limit is preflighted without simplification',()=>{const d=C.blank();d.board.shape='polygon';d.board.points=C.G.circle(30,30,20,513);assert.throws(()=>same(d,()=>X.prepare(d)),/vertices/);});
test('Oversized contours are refused before expensive boundary validation',()=>{const d=C.blank();d.board.shape='polygon';d.board.points=C.G.circle(30,30,20,600);const original=C.G.simple;C.G.simple=()=>{throw Error('Unexpected expensive boundary check');};try{assert.throws(()=>X.prepare(d),/vertices/);}finally{C.G.simple=original;}});
test('CaseBench cutout count limit is preflighted',()=>{const d=C.blank();for(let i=0;i<129;i++)d.cutouts.push({id:'cut'+i,points:C.G.rect(10,10,1,1)});assert.throws(()=>X.prepare(d),/cutouts.*129 \/ 128/);});
test('CaseBench JSON limit counts UTF-8 bytes and does not truncate the file',()=>{const d=C.example();d.assets=[{id:'big',data:'data:image/png;base64,'+'A'.repeat(8388608)}];assert(X.prepare(d).summary.bytes<8388608);assert.throws(()=>X.prepare(d,{includeProjectData:true}),/JSON bytes.*project extras/);});
test('Snapshot is deterministic for an unchanged design, with stable IDs',()=>{const d=C.example();const a=X.prepare(d),b=X.prepare(d);assert.equal(a.json,b.json);assert.equal(a.filename,b.filename);assert.equal(a.summary.bytes,new TextEncoder().encode(a.json).length);});
test('Both board-face stored envelope maxima are summarized without changing bodies',()=>{const d=C.blank();const a=placed(d,'led5');const b=placed(d,'cap-radial');b.side='bottom';const r=X.prepare(d);assert.equal(r.summary.topEnvelopeHeight,a.body.z);assert.equal(r.summary.bottomEnvelopeHeight,b.body.z);});
// Integration fixtures are native snapshots, not a copy of the unavailable
// CASEBENCH importer. Cross-app normalization is a separately disclosed check.
let exampleCount=0;
function walk(dir){for(const item of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,item.name);if(item.isDirectory())walk(p);else if(item.name.endsWith('.json')){const d=JSON.parse(fs.readFileSync(p,'utf8'));if(d.app!=='COPPERBENCH')continue;const normalized=C.validateDoc(d),r=X.prepare(normalized);assertGeometry(normalized,r.document);exampleCount++;}}}
test('All shipped native starter projects keep their placed geometry and block members',()=>{walk(path.join(__dirname,'../examples'));assert(exampleCount>10);});
const fixture=X.prepare(body());fs.mkdirSync(path.join(out,'fixtures','casebench'),{recursive:true});fs.writeFileSync(path.join(out,'fixtures','casebench',fixture.filename),fixture.json);
fs.writeFileSync(path.join(out,'casebench-export-results.json'),JSON.stringify({passed:results.filter(r=>r.pass).length,total:results.length,exampleCount,results},null,2));
console.log(`${results.filter(r=>r.pass).length}/${results.length} CaseBench export checks passed (${exampleCount} shipped native examples)`);
