'use strict';
// Print geometry regressions, independent of the camera/editor tag layout.
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
for(const f of ['core','geometry','vias','font','platforms','maker-parts','carriers','modules','manufacturing','interchange'])require('../src/'+f+'.js');
const C=globalThis.CB,G=C.G,OUT=path.join(__dirname,'output'),DIR=path.join(OUT,'fixtures','compact-polarity');fs.mkdirSync(DIR,{recursive:true});let results=[];
function test(name,fn){try{fn();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.message});console.error('FAIL',name,e.stack);process.exitCode=1;}}
function board(id='diode'){const d=C.blank();d.board.shape='rect';d.board.width=90;d.board.height=65;const p=C.makePart(d,id,45,32);p.label.visible=false;d.parts.push(p);return d;}
const library=C.LIB.filter(f=>f.pads.some(a=>C.polarityRole(f,a)));
function separated(strokes){for(let i=0;i<strokes.length;i++)for(let j=i+1;j<strokes.length;j++){const a=strokes[i],b=strokes[j];if(a.padId===b.padId)continue;for(let ii=1;ii<a.points.length;ii++)for(let jj=1;jj<b.points.length;jj++)assert(G.segSegDist(a.points[ii-1],a.points[ii],b.points[jj-1],b.points[jj])>(a.width+b.width)/2+.05,'Overprinted terminals: '+a.padId+' / '+b.padId);}}
test('Default polarity prints at 0.9 mm with a 0.16 mm stroke, independent of reference text',()=>{const d=board(),p=d.parts[0],o=C.polarityOptions(p);assert.equal(o.size,.9);assert.equal(o.visible,true);assert.equal(o.gap,.7);assert(C.silkStrokes(d).every(s=>s.width===.16&&s.polarity&&s.padId));});
test('Existing explicit print dimensions, offsets and opt-out survive without being reset',()=>{const d=board(),p=d.parts[0];p.polaritySilk={visible:false,size:2,gap:1.3,x:4,y:-2};const expected=JSON.stringify(p);assert.deepEqual(C.polarityOptions(p),p.polaritySilk);C.polarityMarks(p);C.M.files(d);assert.equal(JSON.stringify(p),expected);assert.equal(C.silkStrokes(d).length,0);});
test('All polarized library variants have separate role glyphs, not just editor labels',()=>{assert.equal(library.length,19);for(const f of library){const d=board(f.id),marks=C.polarityMarks(d.parts[0]),strokes=C.silkStrokes(d);assert(marks.length>0,f.id);for(const m of marks)assert(strokes.some(s=>s.padId===m.padId&&s.polarity===m.role),f.id+': '+m.label);separated(strokes);}});
test('All default glyphs clear their own body and every solder opening on either face',()=>{for(const f of library)for(const side of ['top','bottom'])for(const rotation of [0,37,90,180,270]){const d=board(f.id),p=d.parts[0];p.side=side;p.rotation=rotation;const body=G.rect(-p.body.w/2,-p.body.h/2,p.body.w,p.body.h).map(a=>C.world(p,a)),pads=C.pads(d).map(a=>G.padPoly(a,d.profile.maskExpansion+.05));for(const s of C.silkStrokes(d))for(let i=1;i<s.points.length;i++){assert(G.segPolyDist(s.points[i-1],s.points[i],body)>s.width/2,f.id+' body');for(const pad of pads)assert(G.segPolyDist(s.points[i-1],s.points[i],pad)>s.width/2,f.id+' pad');}separated(C.silkStrokes(d));}});
test('RGB anode/cathode variants use four ordered glyph positions rather than overprinting',()=>{for(const id of ['maker-rgb-anode','maker-rgb-cathode']){const d=board(id),p=d.parts[0],marks=C.polarityMarks(p);assert.equal(marks.length,4);for(let i=0;i<marks.length;i++){assert.equal(marks[i].local.x,p.pads[i].x);assert(marks[i].local.y>p.body.h/2+.7);if(i)assert(marks[i].local.x>marks[i-1].local.x);}separated(C.silkStrokes(d));}});
test('Increasing print size spaces adjacent RGB labels without changing pads or nets',()=>{for(const id of ['maker-rgb-anode','maker-rgb-cathode'])for(const size of [.6,.9,1.2,3,10]){const d=board(id),p=d.parts[0],before=JSON.stringify(p.pads);p.polaritySilk={size};separated(C.silkStrokes(d));assert.equal(JSON.stringify(p.pads),before);}});
test('An equivalent vertical multi-terminal footprint gets separated aligned column labels',()=>{const d=board('maker-rgb-anode'),p=d.parts[0];p.pads.forEach(a=>{a.y=a.x;a.x=0;});const m=C.polarityMarks(p);assert(m.every(a=>a.local.x>p.body.w/2));separated(C.silkStrokes(d));});
test('Printing remains strictly component-side through every rotation and flip',()=>{for(const f of library)for(const side of ['top','bottom']){const d=board(f.id),p=d.parts[0];p.side=side;p.rotation=37;const files=C.M.files(d),face=side==='top'?'F':'B',other=side==='top'?'B':'F';assert(C.M.readGerber(files[`board-${face}_Silkscreen.gbr`]).objects.some(a=>a.kind==='line'&&a.polarity==='dark'));assert(!C.M.readGerber(files[`board-${other}_Silkscreen.gbr`]).objects.some(a=>a.polarity==='dark'));}});
test('Native schema 5 preserves roles and gives identical regenerated print geometry',()=>{const d=board('maker-rgb-cathode'),p=d.parts[0];p.side='bottom';p.rotation=90;p.polaritySilk={visible:true,size:.9,gap:.7,x:.2,y:-.1};const again=C.validateDoc(JSON.parse(JSON.stringify(d)));assert.equal(again.schema,5);assert.deepEqual(C.M.files(d),C.M.files(again));});
test('X2, legacy Gerber, KiCad and SVG all include printable role glyphs',()=>{const d=board('led5'),x2=C.M.files(d),rs=C.M.files(d,{x2:false});assert.deepEqual(C.M.readGerber(x2['board-F_Silkscreen.gbr']).objects,C.M.readGerber(rs['board-F_Silkscreen.gbr']).objects);assert(C.M.svg(d).includes('<polyline'));assert(C.K.export(d).includes('F.SilkS'));});
// Fixtures for a separate Python Gerber reader: one component per board removes
// ambiguity about which terminal a retained stroke represents.
for(const f of library)for(const side of ['top','bottom']){const d=board(f.id);d.parts[0].side=side;d.parts[0].rotation=side==='top'?0:37;const dir=path.join(DIR,f.id+'-'+side);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'project.json'),JSON.stringify(d));fs.writeFileSync(path.join(dir,'glyphs.json'),JSON.stringify(C.silkStrokes(d)));for(const [n,t]of Object.entries(C.M.files(d)))if(n.includes('Silkscreen'))fs.writeFileSync(path.join(dir,n),t);}
const demo=C.blank();demo.title='Polarity · compact & printable';demo.board={...demo.board,width:80,height:50};for(const [id,x,y,rot,ref]of [['diode',17,17,0,'D1'],['led5',40,17,90,'D2'],['cap-radial',63,17,0,'C1'],['maker-led-0805',17,35,0,'D3'],['maker-rgb-anode',40,35,0,'D4'],['maker-rgb-cathode',63,35,0,'D5']]){const p=C.makePart(demo,id,x,y);p.rotation=rot;p.ref=ref;demo.parts.push(p);}demo.art.push({id:'heading',kind:'text',text:'POLARITY / ASSEMBLY',x:23,y:4,size:1.4,width:.18,rotation:0,layer:'top'});fs.writeFileSync(path.join(DIR,'demo.json'),JSON.stringify(demo,null,2));
fs.writeFileSync(path.join(OUT,'compact-polarity-results.json'),JSON.stringify({version:C.VERSION,passed:results.filter(r=>r.pass).length,total:results.length,results},null,2));console.log(`${results.filter(r=>r.pass).length}/${results.length} tests passed.`);
