'use strict';
const assert=require('node:assert/strict'), fs=require('node:fs'),path=require('node:path');
for(const f of ['core','geometry','font','platforms','manufacturing','router','interchange'])require('../src/'+f+'.js');
const C=globalThis.CB,G=C.G,R=C.R,M=C.M,K=C.K;
const OUTPUT=path.join(__dirname,'output'), FIXTURES=path.join(OUTPUT,'fixtures');
fs.mkdirSync(FIXTURES,{recursive:true});
let count=0;const results=[];
function test(name,f){const start=Date.now();try{f();results.push({name,pass:true,ms:Date.now()-start});console.log('ok '+(++count)+' - '+name);}catch(e){console.error('NOT OK - '+name,e.stack);process.exitCode=1;results.push({name,pass:false,error:e.message});}}
function near(a,b,e=.00015){assert(Math.abs(a-b)<=e,`${a} != ${b}`);}
function board(w=40,h=30){const d=C.blank();d.board={...d.board,width:w,height:h,shape:'rect'};return d;}
function tp(d,x,y,net,side='top'){const p=C.makePart(d,'testpoint',x,y);p.side=side;p.pads[0].net=net;p.label.visible=false;p.verified=true;p.source='Automated fixture geometry, not a certified purchased component.';d.parts.push(p);return p;}
function trace(d,net,points,layer='top',width=.4){let t={id:C.uid('t'),net,points:points.map(([x,y])=>({x,y})),layer,width,locked:false};d.traces.push(t);return t;}
function pair(){const d=board(),n=C.newNet(d,'TEST');tp(d,7,10,n);tp(d,32,10,n);return{d,n,p:C.pads(d)};}
function errors(d){return G.findings(d).filter(f=>f.severity==='error');}
test('Native schema-2 JSON round-trip preserves an entire document',()=>{let d=C.example();assert.deepEqual(C.validateDoc(JSON.parse(JSON.stringify(d))),d);});
test('All library footprints pass schema validation',()=>{let d=board(200,150);C.LIB.forEach((f,i)=>d.parts.push(C.makePart(d,f,20+(i%6)*25,20+Math.floor(i/6)*25)));C.validateDoc(d);assert(C.LIB.length>=30);});
test('Malformed geometry, unknown schema, and duplicate identities stop import',()=>{for(let mutate of [d=>d.schema=99,d=>d.board.width=NaN,d=>d.parts.push(d.parts[0]),d=>d.profile.clearance=-1,d=>d.art.push({id:'bad',kind:'script',x:0,y:0,layer:'top'})]){let d=C.example();mutate(d);assert.throws(()=>C.validateDoc(d));}});
test('Circular pads cannot silently stretch or turn into incorrect circles',()=>{let d=C.example();d.parts[0].pads[0].shape='circle';d.parts[0].pads[0].h+=1;assert.throws(()=>C.validateDoc(d));});
test('Four rotations and two face flips preserve every pin identity and coordinate',()=>{let d=board(),p=C.makePart(d,'dip8',20,15);d.parts.push(p);let before=C.pads(d);for(let i=0;i<4;i++)p.rotation=(p.rotation+90)%360;p.side='bottom';p.side='top';assert.deepEqual(C.pads(d),before);});
test('Bottom flip reflects physical pin position without changing pin numbering',()=>{let d=board(),p=C.makePart(d,'header4',20,15);d.parts.push(p);let a=C.pads(d);p.side='bottom';let b=C.pads(d);for(let i=0;i<a.length;i++){near(a[i].x+b[i].x,40);assert.equal(a[i].pin,b[i].pin);}});
test('Board resizing does not resize footprints',()=>{let d=C.example(),p=JSON.stringify(d.parts);d.board.width+=20;assert.equal(JSON.stringify(d.parts),p);});
test('Net merges require explicit consent and update copper consistently',()=>{let {d,n,p}=pair(),other=C.newNet(d,'OTHER');d.parts[1].pads[0].net=other;let t=trace(d,other,[[30,10],[32,10]]);assert.throws(()=>C.assignPads(d,p.map(p=>p.id),n));C.assignPads(d,p.map(p=>p.id),n,true);assert.equal(t.net,n);assert.equal(d.nets.length,1);});
test('Deleting copper does not erase intended electrical connectivity',()=>{let {d,n}=pair();trace(d,n,[[7,10],[32,10]]);assert.equal(G.connectivity(d).unrouted,0);d.traces=[];assert.equal(G.connectivity(d).unrouted,1);assert(d.parts.every(p=>p.pads[0].net===n));});
test('A real microscopic break is not considered a completed connection',()=>{let d=board(),n=C.newNet(d,'N');tp(d,5,10,n);tp(d,30,10,n);trace(d,n,[[5,10],[15,10]],'top',.4);trace(d,n,[[15.402,10],[30,10]],'top',.4);assert.equal(G.connectivity(d).unrouted,1);});
test('Different layers stay electrically separate until a through via is added',()=>{let d=board(),n=C.newNet(d,'N');tp(d,5,10,n);tp(d,30,10,n,'bottom');trace(d,n,[[5,10],[20,10]]);trace(d,n,[[20,10],[30,10]],'bottom');assert.equal(G.connectivity(d).unrouted,1);d.vias.push({id:C.uid('v'),x:20,y:10,diameter:.9,drill:.4,net:n});assert.equal(G.connectivity(d).unrouted,0);});
test('Crossed distinct nets are blocking shorts; undersized traces are blocked',()=>{let d=board(),a=C.newNet(d,'A'),b=C.newNet(d,'B');trace(d,a,[[5,15],[30,15]]);trace(d,b,[[15,5],[15,25]],'top',.1);assert(errors(d).some(f=>f.code==='short'));assert(errors(d).some(f=>f.code==='trace-width'));});
test('Exact route checks reject board edges, cutouts, holes and keepouts',()=>{let {d,n}=pair();assert(!G.pathClear(d,[{x:0,y:2},{x:30,y:2}],.4,n,'top').ok);d.cutouts.push({id:C.uid(),points:G.rect(19,9,1,2)});assert(!G.pathClear(d,[{x:7,y:10},{x:32,y:10}],.4,n,'top').ok);d.cutouts=[];d.holes.push({id:C.uid(),x:20,y:10,drill:2,slot:0,rotation:0,plated:false});assert(!G.pathClear(d,[{x:7,y:10},{x:32,y:10}],.4,n,'top').ok);d.holes=[];d.keepouts.push({id:C.uid(),points:G.rect(19,9,1,2),layer:'both'});assert(!G.pathClear(d,[{x:7,y:10},{x:32,y:10}],.4,n,'top').ok);});
test('Direct selected-pin autorouting creates verified copper',()=>{let{d,p}=pair(),r=R.route(d,p[0],p[1]);assert(!r.error);d.traces.push(...r.traces);assert.equal(G.connectivity(d).unrouted,0);assert.equal(errors(d).length,0);});
test('Obstacle-aware A* takes a different path without illegal copper',()=>{let{d,p}=pair();d.keepouts.push({id:C.uid(),points:G.rect(17,7,5,6),layer:'both'});let r=R.route(d,p[0],p[1],{vias:false});assert(!r.error,r.error);assert(r.visited>0);d.traces.push(...r.traces);d.vias.push(...r.vias);assert.equal(errors(d).length,0);assert.equal(G.connectivity(d).unrouted,0);});
test('Blocked autorouting reports failure and never mutates its input',()=>{let{d,p}=pair();d.keepouts.push({id:C.uid(),points:G.rect(17,0,5,30),layer:'both'});let before=JSON.stringify(d),r=R.route(d,p[0],p[1],{maxNodes:8000});assert(r.error);assert.equal(r.traces.length,0);assert.equal(JSON.stringify(d),before);});
test('Two-sided autorouting inserts a real through-via transition',()=>{let{d,n}=pair();d.parts[1].side='bottom';let p=C.pads(d),r=R.route(d,p[0],p[1],{step:.5});assert(!r.error,r.error);assert(r.vias.length>=1);d.traces.push(...r.traces);d.vias.push(...r.vias);assert.equal(G.connectivity(d).unrouted,0);assert.equal(errors(d).length,0);});
test('Multi-pin autowiring produces one physically connected net',()=>{let{d,n}=pair();tp(d,20,22,n);let r=R.routeGroup(d,C.pads(d).map(p=>p.id));assert.equal(r.failures.length,0);d.traces.push(...r.traces);d.vias.push(...r.vias);assert.equal(G.connectivity(d).unrouted,0);assert.equal(errors(d).length,0);});
test('Autowiring already connected pins does not add redundant copper',()=>{let{d,n,p}=pair();trace(d,n,[[7,10],[32,10]]);let r=R.routeGroup(d,p.map(p=>p.id));assert.equal(r.traces.length,0);assert.equal(r.vias.length,0);assert.equal(r.failures.length,0);});
test('Filled zones are actual copper and isolated islands are removed',()=>{let d=board(20,16),n=C.newNet(d,'GND');tp(d,5,8,n);tp(d,15,8,n);let z={id:C.uid('z'),net:n,layer:'top',points:G.rect(2,2,16,12),thermal:false,step:.5};d.zones.push(z);z.fill=R.fillZone(d,z);assert(z.fill.rects.length>0);assert.equal(G.connectivity(d).unrouted,0);assert.equal(errors(d).length,0);d.parts=[];z.fill=R.fillZone(d,z);assert.equal(z.fill.rects.length,0);assert(z.fill.removedIslands>0);});
test('Thermal relief pours connect pads while respecting a different-net obstacle',()=>{let d=board(26,20),n=C.newNet(d,'GND'),v=C.newNet(d,'OTHER');tp(d,6,10,n);tp(d,20,10,n);tp(d,13,10,v);let z={id:C.uid('z'),net:n,layer:'top',points:G.rect(2,2,22,16),thermal:true,gap:.4,spoke:.6,step:.25};d.zones.push(z);z.fill=R.fillZone(d,z);assert(z.fill.rects.length>0);assert.equal(G.connectivity(d).unrouted,0);assert.deepEqual(errors(d),[]);});
test('Stale copper pours block manufacturing generation',()=>{let d=board();d.zones.push({id:C.uid(),layer:'top',net:null,points:G.rect(1,1,10,10),fill:null});assert.throws(()=>M.files(d));assert(errors(d).some(f=>f.code==='zone-stale'));});
test('Excellon plated/non-plated files preserve slot endpoints and tool diameter',()=>{let d=board();d.holes.push({id:'np',x:10,y:12,drill:1,slot:3,rotation:35,plated:false});let fs=M.files(d),dr=Object.entries(fs).find(([n])=>n.includes('NPTH'));assert(dr);let parsed=M.readDrill(dr[1]);assert.equal(parsed.objects[0].kind,'slot');near(G.dist(parsed.objects[0].a,parsed.objects[0].b),3,.000002);near(parsed.objects[0].diameter,1);});
test('Gerber copper, mask, silk, outline and optional paste all reparse',()=>{let d=C.example('mixed'),fs=M.files(d,{paste:true});assert.equal(Object.keys(fs).filter(n=>n.endsWith('.gbr')).length,9);for(const [n,s] of Object.entries(fs))assert((n.endsWith('.drl')?M.readDrill(s):M.readGerber(s)).objects);});
test('Bottom manufacturing layers are not mirrored',()=>{let d=board(),n=C.newNet(d,'N');tp(d,8,11,n,'bottom');let a=M.readGerber(M.files(d)['board-B_Cu.gbr']).objects.find(o=>o.kind==='flash');near(a.x,8);near(a.y,19);});
test('Gerber compatibility export drops attributes but not geometry',()=>{let d=C.example(),a=M.files(d),b=M.files(d,{x2:false});for(const n of Object.keys(a)){if(n.endsWith('.gbr'))assert.deepEqual(M.readGerber(a[n]).objects,M.readGerber(b[n]).objects);}assert(!b['board-F_Cu.gbr'].includes('%TF.'));});
test('Filled silkscreen polygons stay filled after KiCad interchange',()=>{let d=board();d.art.push({id:'a',kind:'poly',x:5,y:5,rotation:0,layer:'bottom',points:G.rect(0,0,3,2),filled:true,width:.2});let a=C.silkRects(d);assert.equal(a.length,1);let imp=K.import(K.export(d)).document;let b=C.silkRects(imp);assert.equal(b.length,1);near(Math.abs(G.area(a[0].poly)),Math.abs(G.area(b[0].poly)));});
test('KiCad subset round-trip preserves flipped/rotated pad and drill coordinates',()=>{let d=board(80,60);for(let i=0;i<4;i++){let p=C.makePart(d,i%2?'soic8':'header4',15+i*15,25);p.rotation=[0,35,90,270][i];p.side=i<2?'top':'bottom';d.parts.push(p);}let a=C.pads(d),b=C.pads(K.import(K.export(d)).document);assert.equal(a.length,b.length);for(let i=0;i<a.length;i++){near(a[i].x,b[i].x);near(a[i].y,b[i].y);near(a[i].drill,b[i].drill);assert.equal(a[i].pin,b[i].pin);assert.equal(a[i].layers,b[i].layers);let pa=G.padPoly(a[i]),pb=G.padPoly(b[i]);near(Math.abs(G.area(pa)),Math.abs(G.area(pb)),.001);}assert.equal(K.import(K.export(d)).document.nets.length,0);});
test('KiCad inner layers, custom pads and explicit manufacturing graphics are rejected',()=>{let d=board();d.parts.push(C.makePart(d,'header2',20,15));let k=K.export(d);assert.throws(()=>K.import(k.replace('(31 "B.Cu" signal)','(1 "In1.Cu" signal) (31 "B.Cu" signal)')));assert.throws(()=>K.import(k.replace('thru_hole rect','thru_hole roundrect')));assert.throws(()=>K.import(k.replace(/\)\s*$/,' (gr_line (start 1 1) (end 2 2) (stroke (width 0.2) (type default)) (layer "F.Mask")))')));});
test('Manufacturing reader rejects unsupported/incomplete input rather than inventing geometry',()=>{assert.throws(()=>M.readGerber('%MOMM*%\nG02X0Y0D01*\nM02*'));assert.throws(()=>M.readDrill('M48\nMETRIC,TZ\nT01C1.0\n%\nT01\nX10Y10\nM30'));assert.throws(()=>M.readGerber('G04 incomplete*'));});
test('Baseline comparison records added, changed, and removed objects',()=>{let d=C.example(),a=C.snapshot(d);d.parts[0].x+=1;d.parts.pop();d.art.push({id:'extra'});let delta=C.compare(d,a);assert(delta.some(x=>x.kind==='Added'));assert(delta.some(x=>x.kind==='Changed'));assert(delta.some(x=>x.kind==='Removed'));});
// A deterministic geometry fixture: these test-pad dimensions are not a purchased-part certification.
function golden(){let d=board();d.title='Geometry proof — two-layer coupon';d.id='golden-coupon';d.created=d.updated='2026-09-17T00:00:00.000Z';let a=C.newNet(d,'TOP_LINK'),b=C.newNet(d,'BOTTOM_LINK'),c=C.newNet(d,'VIA_LINK');tp(d,8,8,a);tp(d,20,8,a);trace(d,a,[[8,8],[20,8]]);tp(d,8,19,b,'bottom');tp(d,22,19,b,'bottom');trace(d,b,[[8,19],[22,19]],'bottom',.6);tp(d,8,25,c,'bottom');tp(d,22,25,c);trace(d,c,[[8,25],[14,25]],'bottom');trace(d,c,[[14,25],[22,25]]);d.vias.push({id:'golden-via',x:14,y:25,diameter:1,drill:.5,net:c,tented:false});let h=C.makePart(d,'header2',30,12);h.rotation=90;h.pads[0].net=a;h.pads[1].net=b;h.label.visible=false;h.verified=true;d.parts.push(h);let p=C.pads(d).filter(p=>p.partId===h.id);trace(d,a,[[20,8],[25,8],[30,p[0].y]]);trace(d,b,[[22,19],[30,19],[30,p[1].y]],'bottom');d.holes.push({id:'golden-hole',x:3,y:3,drill:2,slot:0,rotation:0,plated:false},{id:'golden-slot',x:36,y:25,drill:1.2,slot:2,rotation:30,plated:false});d.art.push({id:'golden-top-text',kind:'text',text:'TOP',x:5,y:12,size:1.5,width:.2,rotation:0,layer:'top',mirror:false},{id:'golden-bottom-text',kind:'text',text:'BOTTOM',x:19,y:4,size:1.1,width:.18,rotation:0,layer:'bottom',mirror:false});d.evidence.push({id:'fixture-note',text:'Software geometry fixture. Not manufacturer-approved or physically fabricated.'});return d;}
test('Golden two-layer coupon has no blocking geometry findings',()=>{const d=golden();assert.deepEqual(errors(d),[]);C.validateDoc(d);fs.mkdirSync(path.join(FIXTURES,'golden-fabrication'),{recursive:true});fs.writeFileSync(path.join(FIXTURES,'golden-coupon.json'),JSON.stringify(d,null,2));for(const [n,t] of Object.entries(M.files(d,{paste:true})))fs.writeFileSync(path.join(FIXTURES,'golden-fabrication',n),t);fs.writeFileSync(path.join(FIXTURES,'golden-coupon.kicad_pcb'),K.export(d));});
for(const n of ['starter','smd','mixed'])fs.writeFileSync(path.join(FIXTURES,n+'.json'),JSON.stringify(C.example(n),null,2));
fs.writeFileSync(path.join(OUTPUT,'core-results.json'),JSON.stringify({date:new Date().toISOString(),node:process.version,passed:results.filter(r=>r.pass).length,total:results.length,results},null,2));
console.log(`\n${results.filter(r=>r.pass).length}/${results.length} tests passed.`);
