'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
for(const f of ['core','geometry','vias','font','platforms','maker-parts','carriers','modules','block-catalog','blocks','router','planes','manufacturing','editing','export-review'])require('../src/'+f+'.js');
const C=globalThis.CB,G=C.G,E=C.Edit,results=[],out=path.join(__dirname,'output');fs.mkdirSync(out,{recursive:true});
function test(name,fn){try{fn();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.stack});console.error('FAIL',name,e.stack);process.exitCode=1;}}
function b(){const d=C.blank();d.board={...d.board,width:60,height:45,shape:'rect'};d.settings.grid=1;return d;}
function t(d,points,net,width=.4,layer='top'){const o={id:C.uid('t'),points:points.map(([x,y])=>({x,y})),net,width,layer,locked:false};d.traces.push(o);return o;}
function p(d,x,y,n,layer='top'){const a=C.makePart(d,'testpoint',x,y);a.pads[0].net=n;a.label.visible=false;a.verified=true;a.side=layer;d.parts.push(a);return a;}
function pair(){const d=b(),n=C.newNet(d,'LINK'),a=p(d,10,10,n),z=p(d,45,10,n),line=t(d,[[10,10],[45,10]],n);return {d,n,a,z,line};}
function good(r){assert(r.ok,r.reason);return r.document;}
function bad(r,reason){assert.equal(r.ok,false);if(reason)assert.match(r.reason,reason);}
function same(d,fn){const json=JSON.stringify(d);const r=fn();assert.equal(JSON.stringify(d),json);return r;}

test('Successful and failed proposals never mutate the input document',()=>{const {d,a}=pair();good(same(d,()=>E.moveConnected(d,a.id,{x:10,y:20})));bad(same(d,()=>E.moveConnected(d,a.id,{x:-20,y:20})));});
test('Cleanup removes duplicate points and forward collinear points',()=>assert.deepEqual(E.cleanPoints([{x:1,y:1},{x:1,y:1},{x:2,y:2},{x:3,y:3}]),[{x:1,y:1},{x:3,y:3}]));
test('Cleanup does not erase a reversal',()=>assert.equal(E.cleanPoints([{x:1,y:1},{x:3,y:1},{x:2,y:1}]).length,3));
test('Straight routes report no cleanup needed',()=>{const {d,line}=pair();bad(E.trace(d,line.id,{kind:'clean'}),/No geometry/);});
test('Insert a collinear handle without immediately removing it',()=>{const {d,line}=pair();const r=good(E.trace(d,line.id,{kind:'insert',index:0,point:{x:25,y:10}}));assert.equal(r.traces[0].points.length,3);});
test('Move a newly inserted corner; endpoint pad contacts remain connected',()=>{const {d,line}=pair();const ins=good(E.trace(d,line.id,{kind:'insert',index:0,point:{x:25,y:10}}));const r=good(E.trace(ins,line.id,{kind:'vertex',index:1,point:{x:25,y:18}}));assert.equal(G.connectivity(r).unrouted,0);});
test('Manual endpoint move cannot detach existing pad',()=>{const {d,line}=pair();bad(E.trace(d,line.id,{kind:'vertex',index:0,point:{x:18,y:20}}),/disconnect/);});
test('One-segment slide creates doglegs and keeps original endpoints',()=>{const {d,line}=pair();const r=good(E.trace(d,line.id,{kind:'slide',index:0,point:{x:27,y:20}}));assert.equal(r.traces[0].points.length,4);assert.deepEqual(r.traces[0].points[0],{x:10,y:10});assert.deepEqual(r.traces[0].points.at(-1),{x:45,y:10});assert.equal(G.connectivity(r).unrouted,0);});
test('A sideways slide cannot silently lose a T junction',()=>{const {d,n,line}=pair();p(d,25,25,n);t(d,[[25,25],[25,10]],n);bad(E.trace(d,line.id,{kind:'slide',index:0,point:{x:27,y:5}}),/disconnect/);});
test('Preview-only ghost may be invalid but final validation rejects it',()=>{const {d,line}=pair();const op={kind:'slide',index:0,point:{x:20,y:-10}};assert(E.trace(d,line.id,{...op,previewOnly:true}).ok);bad(E.trace(d,line.id,op));});
test('Cannot remove a trace endpoint',()=>{const {d,line}=pair();bad(E.trace(d,line.id,{kind:'remove',index:0}),/Endpoints/);});
test('Remove an interior handle after cleanup preserves net and copper',()=>{const {d,line}=pair();line.points.splice(1,0,{x:25,y:10});const r=good(E.trace(d,line.id,{kind:'remove',index:1}));assert.equal(r.traces[0].points.length,2);assert.equal(r.traces[0].net,line.net);});
test('Replace a selected section, preserving endpoints and line identity',()=>{const {d,line}=pair();const r=good(E.trace(d,line.id,{kind:'replace',start:0,end:1,points:[{x:15,y:15},{x:40,y:15}]}));assert.equal(r.traces[0].id,line.id);assert.equal(r.traces[0].points.length,4);});
test('Bad indices, nonfinite points, too many replacement waypoints fail',()=>{const {d,line}=pair();for(const op of [{kind:'insert',index:9,point:{x:1,y:2}},{kind:'vertex',index:0,point:{x:NaN,y:2}},{kind:'replace',start:1,end:0,points:[]},{kind:'replace',start:0,end:1,points:Array(101).fill({x:20,y:20})}])bad(E.trace(d,line.id,op));});
test('Locked routes reject every geometry operation',()=>{const {d,line}=pair();line.locked=true;for(const op of [{kind:'clean'},{kind:'vertex',index:0,point:{x:20,y:20}},{kind:'slide',index:0,point:{x:20,y:20}}])bad(E.trace(d,line.id,op),/Unlock/);});
test('Width edit is validated against minimum trace width',()=>{const {d,line}=pair();bad(E.width(d,line.id,.01));good(E.width(d,line.id,.8));bad(E.width(d,line.id,NaN));});
test('Widening cannot short or violate clearance to another net',()=>{const {d,line}=pair();const other=C.newNet(d,'OTHER');t(d,[[15,11],[40,11]],other);bad(E.width(d,line.id,2));});
test('Segment width splits only selected geometry; neighbouring widths survive',()=>{const {d,line}=pair();line.points.splice(1,0,{x:20,y:10},{x:35,y:10});const r=good(E.width(d,line.id,.8,'segment',1));assert.equal(r.traces.length,3);assert.equal(r.traces.find(x=>x.id===line.id).width,.8);assert.equal(r.traces.filter(x=>x.width===.4).length,2);assert.equal(G.connectivity(r).unrouted,0);});
test('Split trace pieces retain block membership',()=>{const {d,line}=pair();line.points.splice(1,0,{x:20,y:10},{x:35,y:10});d.blockInstances=[{id:'b1',label:'B1',name:'test',templateId:'test',x:20,y:20,rotation:0,members:[line.id],ports:[],notes:[]}];const r=good(E.width(d,line.id,.8,'segment',1));assert(r.traces.every(t=>r.blockInstances[0].members.includes(t.id)));});
test('Connected selection follows hard copper through a via, not airwires',()=>{const {d,n,line}=pair();d.vias.push({id:'v1',x:25,y:10,net:n,diameter:1,drill:.4,tented:true,locked:false});const other=t(d,[[25,10],[25,25]],n,.4,'bottom');const isolated=t(d,[[50,30],[55,30]],n);const ids=E.connectedCopper(d,line.id);assert(ids.includes('v1')&&ids.includes(other.id));assert(!ids.includes(isolated.id));});
test('Whole-net and touching-route widths have distinct scopes',()=>{const {d,n,line}=pair();const isolated=t(d,[[15,30],[40,30]],n);const connected=good(E.width(d,line.id,.8,'connected'));assert.equal(connected.traces.find(t=>t.id===isolated.id).width,.4);const all=good(E.width(d,line.id,.8,'net'));assert(all.traces.every(t=>t.width===.8));});
test('Whole-net width does not skip locked traces',()=>{const {d,n,line}=pair();t(d,[[15,30],[40,30]],n).locked=true;bad(E.width(d,line.id,.8,'net'),/locked/);});
test('Connected part drag preserves pin identity, net, and trace width',()=>{const {d,a,line}=pair();const r=good(E.moveConnected(d,a.id,{x:10,y:20}));assert.equal(r.parts[0].id,a.id);assert.equal(r.parts[0].pads[0].number,a.pads[0].number);assert.equal(r.traces[0].net,line.net);assert.equal(r.traces[0].width,line.width);assert.equal(G.connectivity(r).unrouted,0);});
test('Connected part drag supports bottom-side pad transforms',()=>{const {d,a,z,line}=pair();a.side=z.side=line.layer='bottom';a.rotation=90;const r=good(E.moveConnected(d,a.id,{x:10,y:20}));assert.equal(r.traces[0].layer,'bottom');assert.equal(G.connectivity(r).unrouted,0);});
test('Via drag preserves attached top and bottom routes',()=>{const d=b(),n=C.newNet(d,'LINK');p(d,10,10,n);p(d,45,30,n,'bottom');d.vias.push({id:'via',x:30,y:10,net:n,diameter:1,drill:.4,tented:true,locked:false});t(d,[[10,10],[30,10]],n);t(d,[[30,10],[45,30]],n,.8,'bottom');const r=good(E.moveConnected(d,'via',{x:30,y:20}));assert.equal(G.connectivity(r).unrouted,0);assert.equal(r.vias[0].drill,.4);assert.deepEqual(r.traces.map(t=>t.width),[.4,.8]);});
test('Connected move of existing multi-segment route retains fixed interior points',()=>{const {d,a,line}=pair();line.points=[{x:10,y:10},{x:15,y:15},{x:35,y:15},{x:45,y:10}];const r=good(E.moveConnected(d,a.id,{x:10,y:20}));assert(r.traces[0].points.some(p=>p.x===35&&p.y===15));assert.equal(G.connectivity(r).unrouted,0);});
test('Connected drag rejects an off-centre terminal contact',()=>{const {d,a,line}=pair();line.points[0].x+=.2;bad(E.moveConnected(d,a.id,{x:10,y:20}),/centered/);});
test('Connected drag rejects through-middle contact',()=>{const {d,a,line}=pair();line.points[0]={x:7,y:10};bad(E.moveConnected(d,a.id,{x:10,y:20}),/centered/);});
test('Locked component and locked attached trace stop connected drag',()=>{const {d,a,line}=pair();a.locked=true;bad(E.moveConnected(d,a.id,{x:10,y:20}),/Unlock/);a.locked=false;line.locked=true;bad(E.moveConnected(d,a.id,{x:10,y:20}),/locked/);});
test('Moving into a foreign pad or outside substrate is rejected',()=>{const {d,a}=pair();p(d,10,20,C.newNet(d,'OTHER'));bad(E.moveConnected(d,a.id,{x:10,y:20}));bad(E.moveConnected(d,a.id,{x:-10,y:20}));});
test('Attached plane net is explicitly unsupported by connected drag',()=>{const {d,n,a}=pair();C.Planes.set(d,'top',n);bad(E.moveConnected(d,a.id,{x:10,y:20}),/copper pour/);});
test('Unrelated pours are invalidated by accepted geometry changes',()=>{const {d,line}=pair();C.Planes.set(d,'bottom',C.newNet(d,'GND'));d.zones[0].fill={rects:[],area:0};const r=good(E.width(d,line.id,.8));assert.equal(r.zones[0].fill,null);});
test('Stationary part, unknown ID, nonfinite coordinate fail without mutation',()=>{const {d,a}=pair();for(const [id,pos]of [[a.id,{x:10,y:10}],['unknown',{x:1,y:1}],[a.id,{x:Infinity,y:1}]])bad(same(d,()=>E.moveConnected(d,id,pos)));});
test('Printable reference and polarity are separate movable groups',()=>{const d=b(),a=C.makePart(d,'diode',30,20);d.parts.push(a);const groups=E.markGroups(d,'top');assert(groups.some(g=>g.kind==='reference'));assert(groups.some(g=>g.kind==='polarity'));});
test('Moving reference never moves component pads or polarity settings',()=>{const d=b(),a=C.makePart(d,'diode',30,20);d.parts.push(a);const pads=C.pads(d),pol=C.polarityOptions(a);const r=good(E.moveMark(d,a.id,'reference',{x:4,y:3}));assert.deepEqual(C.pads(r),pads);assert.deepEqual(C.polarityOptions(r.parts[0]),pol);});
test('Printed polarity movement respects rotation and bottom-side mirroring',()=>{for(const side of ['top','bottom'])for(const rotation of [0,90,180,270]){const d=b(),a=C.makePart(d,'diode',30,20);a.side=side;a.rotation=rotation;d.parts.push(a);const before=E.markGroups(d,side).find(g=>g.kind==='polarity').points[0],r=good(E.moveMark(d,a.id,'polarity',{x:3,y:-2})),after=E.markGroups(r,side).find(g=>g.kind==='polarity').points[0];assert(Math.abs(after.x-before.x-3)<.001);assert(Math.abs(after.y-before.y+2)<.001);assert.deepEqual(C.pads(r),C.pads(d));}});
test('Locked printed markings cannot be dragged',()=>{const d=b(),a=C.makePart(d,'diode',30,20);a.locked=true;d.parts.push(a);bad(E.moveMark(d,a.id,'polarity',{x:3,y:2}),/Unlock/);});
test('Accepted edits survive schema-5 JSON round-trip',()=>{const {d,a}=pair();const r=good(E.moveConnected(d,a.id,{x:10,y:20}));const saved=C.validateDoc(JSON.parse(JSON.stringify(r)));assert.equal(saved.schema,5);assert.deepEqual(saved.traces,r.traces);});
test('Library and block collection remain intact',()=>{assert.equal(C.LIB.length,193);assert.equal(C.BLOCK_CATALOG.length,6);});
// Reference board available for separate parser/CAM inspection, not approval.
const fx=pair(),ref=good(E.moveConnected(fx.d,fx.a.id,{x:10,y:20}));ref.title='v1.7 connected edit reference';ref.parts.forEach(p=>p.label.visible=true);
const folder=path.join(out,'fixtures','editing');fs.mkdirSync(folder,{recursive:true});
fs.writeFileSync(path.join(folder,'project.json'),JSON.stringify(ref,null,2));
for(const [name,text]of Object.entries(C.M.files(ref)))fs.writeFileSync(path.join(folder,name),text);
fs.writeFileSync(path.join(out,'editing-results.json'),JSON.stringify({passed:results.filter(r=>r.pass).length,total:results.length,results},null,2));
console.log(`${results.filter(r=>r.pass).length}/${results.length} editing checks passed`);
