'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
for(const f of ['core','geometry','vias','font','platforms','maker-parts','carriers','modules','block-catalog','blocks','manufacturing','export-review'])require('../src/'+f+'.js');
const C=CB,R=C.Review,results=[],out=path.join(__dirname,'output');
function test(name,fn){try{fn();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.stack});console.error('FAIL',name,e.stack);process.exitCode=1;}}
function board(){const d=C.blank();d.board={...d.board,width:60,height:40,shape:'rect'};return d;}
function silk(d,layer='top'){d.art.push({id:C.uid('art'),kind:'text',text:'PCB 1.7',x:30,y:10,size:2,rotation:0,layer,locked:false});}
const inspect=(d,f)=>R.inspect(d,f||C.M.files(d));
test('Empty silk on an undecorated board is not a false missing-art error',()=>{const r=inspect(board());assert(r.valid);assert(r.silkscreen.every(s=>s.samples===0));});
test('Top and bottom silk text survives actual text readback',()=>{const d=board();silk(d);silk(d,'bottom');const r=inspect(d);assert(r.valid);assert(r.silkscreen.every(s=>s.samples&&s.surviving===s.samples));});
test('Each required generated layer is checked independently',()=>{const d=board(),files=C.M.files(d);for(const name of Object.keys(files)){const bad={...files};delete bad[name];const r=inspect(d,bad);assert(!r.valid,name);}});
test('Malformed Gerber is reported without pretending it was inspected',()=>{const d=board(),files=C.M.files(d);files['board-F_Cu.gbr']='not gerber';assert(!inspect(d,files).valid);});
test('Print-enabled source with dark output removed triggers invariant failure',()=>{const d=board();silk(d);const files=C.M.files(d);const parts=files['board-F_Silkscreen.gbr'].split('%LPC*%');parts[0]=parts[0].replace(/D01\*/g,'D02*');files['board-F_Silkscreen.gbr']=parts.join('%LPC*%');assert(inspect(d,files).errors.some(e=>e.includes('no dark export')));});
test('All-ink-erasing clear rectangle triggers a prominent sampled warning',()=>{const d=board();silk(d);const files=C.M.files(d);files['board-F_Silkscreen.gbr']=files['board-F_Silkscreen.gbr'].replace('M02*','%LPC*%\nG36*\nX0Y0D02*\nX60000000Y0D01*\nX60000000Y40000000D01*\nX0Y40000000D01*\nX0Y0D01*\nG37*\nM02*');const r=inspect(d,files);assert.equal(r.silkscreen[0].surviving,0);assert(r.warnings.some(w=>w.includes('none of the sampled')));});
test('Printed text entirely outside board is flagged as zero retained samples',()=>{const d=board();silk(d);d.art[0].x=80;const r=inspect(d);assert.equal(r.silkscreen[0].surviving,0);assert(r.silkscreen[0].fullyClippedOwners.includes(d.art[0].id));});
test('Some clipped strokes do not incorrectly label the entire layer empty',()=>{const d=board();silk(d);d.art[0].x=-4;const r=inspect(d);assert(r.silkscreen[0].surviving>0);assert(r.silkscreen[0].clipped>0);});
test('Via drills and NPTH slots are compared by coordinates and diameter',()=>{const d=board();d.vias=[{id:'v1',x:25,y:20,diameter:1,drill:.4,net:null,locked:false,tented:false}];d.holes=[{id:'h1',x:10,y:25,drill:2,slot:4,rotation:90,locked:false}];const r=inspect(d);assert(r.valid,r.errors);assert.equal(r.files.find(f=>f.name.endsWith('NPTH.drl')).slots,1);assert.equal(r.files.find(f=>f.name.endsWith('PTH.drl')).drills,1);});
test('Missing drill file cannot be exported as matching the design',()=>{const d=board();d.holes=[{id:'h',x:20,y:20,drill:2,slot:0,rotation:0,locked:false}];const f=C.M.files(d);delete f['board-NPTH.drl'];assert(inspect(d,f).errors.some(e=>e.includes('drill count')));});
test('Same drill count with shifted coordinates is rejected',()=>{const d=board();d.holes=[{id:'h',x:20,y:20,drill:2,slot:0,rotation:0,locked:false}];const f=C.M.files(d);f['board-NPTH.drl']=f['board-NPTH.drl'].replace('X20.000000','X21.000000');assert(inspect(d,f).errors.some(e=>e.includes('coordinates')));});
test('Changed drill diameter is rejected',()=>{const d=board();d.holes=[{id:'h',x:20,y:20,drill:2,slot:0,rotation:0,locked:false}];const f=C.M.files(d);f['board-NPTH.drl']=f['board-NPTH.drl'].replace('C2.000000','C2.500000');assert(!inspect(d,f).valid);});
test('Changed outline bounds are rejected',()=>{const d=board(),f=C.M.files(d);f['board-Edge_Cuts.gbr']=f['board-Edge_Cuts.gbr'].replaceAll('X60000000','X61000000');assert(inspect(d,f).errors.some(e=>e.includes('outline')));});
test('Gerber region contours use UNION even with nested or reversed paths',()=>{const outer=[{x:0,y:0},{x:10,y:0},{x:10,y:10},{x:0,y:10},{x:0,y:0}],inner=[{x:4,y:4},{x:4,y:6},{x:6,y:6},{x:6,y:4},{x:4,y:4}];assert(R.inkTester({objects:[{kind:'region',polarity:'dark',contours:[outer,inner]}]})({x:5,y:5}));});
test('Later dark geometry can restore ink removed by a clear operation',()=>{const objects=[{kind:'flash',x:10,y:10,shape:'C',sizes:[6],polarity:'dark'},{kind:'flash',x:10,y:10,shape:'C',sizes:[4],polarity:'clear'},{kind:'flash',x:10,y:10,shape:'C',sizes:[1],polarity:'dark'}];const ink=R.inkTester({objects});assert(ink({x:10,y:10}));assert(!ink({x:11,y:10}));assert(ink({x:12.5,y:10}));});
test('Review works for compatibility Gerber and optional paste files',()=>{const d=board();silk(d);const r=inspect(d,C.M.files(d,{x2:false,paste:true}));assert(r.valid);assert.equal(r.files.filter(f=>f.name.includes('Paste')).length,2);});
test('Report is tied to the design identity and explicitly not CAM approval',()=>{const d=board(),r=inspect(d);assert.equal(r.projectId,d.id);assert.equal(r.appVersion,C.VERSION);assert.equal(r.designUpdated,d.updated);assert.equal(r.schema,5);assert.match(r.qualification.independentCAM,/not established/);});
test('Inspection leaves source document and generated text unchanged',()=>{const d=board();silk(d);const files=C.M.files(d),before=JSON.stringify([d,files]);inspect(d,files);assert.equal(JSON.stringify([d,files]),before);});
fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'export-review-results.json'),JSON.stringify({passed:results.filter(r=>r.pass).length,total:results.length,results},null,2));console.log(`${results.filter(r=>r.pass).length}/${results.length} export checks passed`);
