'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
for(const f of ['core','geometry','vias','font','platforms','manufacturing','router','planes','interchange'])require('../src/'+f+'.js');
const C=globalThis.CB,G=C.G,P=C.Planes,OUT=path.join(__dirname,'output');fs.mkdirSync(OUT,{recursive:true});const results=[];
function test(name,f){const t=Date.now();try{f();results.push({name,pass:true,ms:Date.now()-t});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.message});console.error('FAIL',name,e.stack);process.exitCode=1;}}
function board(w=32,h=24){const d=C.blank();d.board={...d.board,width:w,height:h,shape:'rect'};d.settings.grid=.5;return d;}
function pad(d,x,y,net=null,side='top',th=false){const p=C.makePart(d,'testpoint',x,y);p.side=side;p.pads[0].net=net;p.pads[0].drill=th?.8:0;p.label.visible=false;p.verified=true;d.parts.push(p);return p;}
function seed(side='bottom'){const d=board(),n=C.newNet(d,'GND');pad(d,6,6,n,'top',true);P.set(d,side,n);return{d,n};}
function linkFixture(){const {d,n}=seed(),p=pad(d,17,13,null);return{d,n,p};}
function fill(d){P.refill(d);return d;}
function bad(d,codes=['short','clearance','copper-edge','hole-spacing','hole-copper','keepout']){return G.findings(d).filter(f=>codes.includes(f.code));}
function saveFixture(name,d){const dir=path.join(OUT,'fixtures','planes',name);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'project.json'),JSON.stringify(d,null,2));for(const [name,text]of Object.entries(C.M.files(d)))fs.writeFileSync(path.join(dir,name),text);}
test('Each face accepts one explicit net or routing-only without assigning component pins',()=>{const d=board(),g=C.newNet(d,'GND'),v=C.newNet(d,'+5V'),p=pad(d,12,12);P.set(d,'top',v);P.set(d,'bottom',g);assert.equal(P.list(d).length,2);assert.equal(p.pads[0].net,null);assert.throws(()=>P.set(d,'both',g));assert.throws(()=>P.set(d,'top','missing'));});
test('Bottom-ground preset preserves manual zones and reuses an existing ground net',()=>{const d=board(),g=C.newNet(d,'ground');d.zones.push({id:'manual',layer:'top',net:g,points:G.rect(2,2,8,8),step:.25,gap:.3,spoke:.5});assert.equal(P.groundPreset(d),g);assert.equal(P.get(d,'top'),null);assert.equal(P.get(d,'bottom').net,g);assert(d.zones.some(z=>z.id==='manual'));assert.equal(d.nets.length,1);});
test('Changing a plane updates the same object, never old pad/trace/via nets',()=>{const{d,n}=seed(),p=d.parts[0],v=C.V.add(d,{x:12,y:6},{net:n}),b=C.newNet(d,'POWER'),id=P.get(d,'bottom').id;P.set(d,'bottom',b);assert.equal(P.get(d,'bottom').id,id);assert.equal(d.zones.length,1);assert.equal(p.pads[0].net,n);assert.equal(v.net,n);});
test('Removing a managed plane preserves pins, traces and manually placed vias',()=>{const{d,n}=seed();C.V.add(d,{x:12,y:6},{net:n});const before=JSON.stringify([d.parts,d.vias]);P.set(d,'bottom',null);assert.equal(d.zones.length,0);assert.equal(JSON.stringify([d.parts,d.vias]),before);});
test('Board resize updates full-plane outlines without stretching footprints',()=>{const{d}=seed();fill(d);const before=JSON.stringify(d.parts);d.board.width=42;P.sync(d);assert.equal(P.get(d,'bottom').fill,null);assert.deepEqual(P.get(d,'bottom').points,G.outline(d));assert.equal(JSON.stringify(d.parts),before);});
test('Managed outline follows circles and custom polygon boards',()=>{const{d}=seed();for(const shape of ['circle','polygon']){d.board.shape=shape;d.board.points=[{x:0,y:0},{x:32,y:0},{x:27,y:24},{x:0,y:24}];P.sync(d);assert.deepEqual(P.get(d,'bottom').points,G.outline(d));}});
test('Native schema 4 preserves planes, settings and actual fill geometry',()=>{const{d}=seed();fill(d);const a=C.validateDoc(JSON.parse(JSON.stringify(d)));assert.equal(a.schema,5);assert.deepEqual(a,d);});
test('Schema 2 migrates with no invented planes and no mutation of the old file',()=>{const d=board();d.schema=2;delete d.settings.autoPlanes;const a=C.validateDoc(d);assert.equal(a.schema,5);assert.equal(a.settings.autoPlanes,true);assert.equal(P.list(a).length,0);assert.equal(d.schema,2);assert.equal(d.settings.autoPlanes,undefined);});
test('Duplicate, both-face and malformed managed planes are rejected on import',()=>{for(const change of [d=>d.zones.push({...C.clone(d.zones[0]),id:'dup'}),d=>d.zones[0].layer='both',d=>d.zones[0].boardPlane='yes']){const{d}=seed();change(d);assert.throws(()=>C.validateDoc(d));}});
test('Through-hole lead contacts an opposite-face plane without an extra via',()=>{const{d}=seed();const result=P.planConnections(d,[d.parts[0].id+':0'],'bottom');assert.equal(result.vias.length,0);assert.equal(result.traces.length,0);assert.equal(P.status(result.document)[0].connected,1);});
test('Same-face surface-mount lead makes direct contact after adopting the plane net',()=>{const{d}=seed();const p=pad(d,17,13,null,'bottom'),a=P.planConnections(d,[p.id+':0'],'bottom');assert.equal(a.assigned.length,1);assert.equal(a.vias.length,0);assert.equal(a.traces.length,0);assert.equal(p.pads[0].net,null);assert.equal(P.status(a.document)[0].connected,2);});
test('Opposite-face surface-mount attachment is a pure short-trace-plus-via proposal',()=>{const{d,p}=linkFixture(),before=JSON.stringify(d),a=P.planConnections(d,[p.id+':0'],'bottom');assert.equal(JSON.stringify(d),before);assert.equal(a.vias.length,1);assert.equal(a.traces.length,1);assert.equal(a.traces[0].layer,'top');assert(G.pointPolyDist(a.vias[0],G.padPoly(C.getPad(d,p.id+':0')))>a.vias[0].diameter/2);assert.equal(P.status(a.document)[0].connected,2);assert.deepEqual(bad(a.document),[]);});
test('Existing different-net copper under a selected lead blocks attachment without mutation',()=>{const{d,p}=linkFixture();d.traces.push({id:'crossing',net:C.newNet(d,'OTHER'),layer:'top',width:.4,points:[{x:14,y:13},{x:20,y:13}]});const before=JSON.stringify(d);assert.throws(()=>P.planConnections(d,[p.id+':0'],'bottom'),/clearance conflicts/);assert.equal(JSON.stringify(d),before);});
test('Net conflicts fail without reassigning pins or adding partial copper',()=>{const{d,p}=linkFixture();p.pads[0].net=C.newNet(d,'POWER');const before=JSON.stringify(d);assert.throws(()=>P.planConnections(d,[p.id+':0'],'bottom'),/never merge nets/);assert.equal(JSON.stringify(d),before);});
test('Repeating a verified plane attachment adds no extra traces or drills',()=>{const{d,p}=linkFixture(),first=P.planConnections(d,[p.id+':0'],'bottom'),second=P.planConnections(first.document,[p.id+':0'],'bottom');assert.equal(second.vias.length,0);assert.equal(second.traces.length,0);});
test('Nearby plane-connected via is reused instead of drilling another',()=>{const{d,n,p}=linkFixture();C.V.add(d,{x:21,y:13},{net:n});const a=P.planConnections(d,[p.id+':0'],'bottom');assert.equal(a.vias.length,0);assert.equal(a.traces.length,1);assert.equal(a.steps[0].kind,'reused-via');});
test('Multiple picked leads produce a single all-or-nothing plan',()=>{const{d,p}=linkFixture(),q=pad(d,24,18),before=JSON.stringify(d),a=P.planConnections(d,[p.id+':0',q.id+':0'],'bottom');assert.equal(a.steps.length,2);assert.equal(P.status(a.document)[0].connected,3);assert.equal(JSON.stringify(d),before);});
test('A conflict anywhere in a multi-lead request leaves every lead untouched',()=>{const{d,p}=linkFixture(),q=pad(d,24,18,C.newNet(d,'OTHER')),before=JSON.stringify(d);assert.throws(()=>P.planConnections(d,[p.id+':0',q.id+':0'],'bottom'));assert.equal(JSON.stringify(d),before);});
test('Blocked local via sites report failure without a fake electrical connection',()=>{const{d,p}=linkFixture();d.keepouts.push({id:'block',layer:'both',points:G.rect(8,3,24,21)});const before=JSON.stringify(d);assert.throws(()=>P.planConnections(d,[p.id+':0'],'bottom'),/no verified local connection|clearance conflicts/);assert.equal(JSON.stringify(d),before);});
test('Bare plane with no seed copper remains empty, not a fictitious ground region',()=>{const d=board();P.groundPreset(d);fill(d);const a=P.status(d)[0];assert.equal(a.state,'empty');assert.equal(a.area,0);assert.equal(a.connected,0);});
test('A copper keepout splits a nominal net into two detected plane regions',()=>{const{d,n}=seed();pad(d,26,8,n,'top',true);d.keepouts.push({id:'divider',layer:'both',points:G.rect(15,0,2,24)});fill(d);assert.equal(P.status(d)[0].regions,2);assert(G.findings(d).some(f=>f.code==='plane-split'));assert.equal(G.connectivity(d).unrouted,1);saveFixture('split',d);});
test('Same-name planes on opposite faces are not connected without a plated path',()=>{const d=board(),n=C.newNet(d,'GND'),a=pad(d,7,12,n),b=pad(d,25,12,n,'bottom');P.groundPreset(d,true);fill(d);assert.equal(G.connectivity(d).unrouted,1);const out=P.planConnections(d,[a.id+':0'],'bottom');assert.equal(out.vias.length,1);assert.equal(G.connectivity(out.document).unrouted,0);});
test('Board-plane assignment survives explicit whole-net merges',()=>{const{d,n}=seed(),v=C.newNet(d,'POWER'),p=pad(d,25,6,v);P.set(d,'top',v);C.assignPads(d,[d.parts[0].id+':0',p.id+':0'],n,true);assert(P.list(d).every(z=>z.net===n));C.validateDoc(d);});
test('New signal routing can carve managed planes, but existing signal copper still blocks',()=>{const{d,n}=seed('top'),signal=C.newNet(d,'SIG');fill(d);const points=[{x:10,y:14},{x:24,y:14}],before=P.get(d,'top').fill.area;assert(G.pathClear(d,points,.4,signal,'top').ok);d.traces.push({id:'sig',net:signal,layer:'top',width:.4,points});fill(d);assert(P.get(d,'top').fill.area<before);assert.deepEqual(bad(d),[]);assert(!G.pathClear(d,[{x:17,y:10},{x:17,y:18}],.4,n,'top').ok);});
test('Local manual pours keep priority over different-net whole-board copper',()=>{const{d,n}=seed('top'),v=C.newNet(d,'LOCAL');pad(d,23,16,v,'top',true);d.zones.push({id:'local',net:v,layer:'top',points:G.rect(19,12,10,9),thermal:false,step:.25,gap:.3,spoke:.5});fill(d);assert(d.zones.find(z=>z.id==='local').fill.area>20);assert.deepEqual(bad(d),[]);});
test('Plane fill clears both internal cutouts and non-plated mounting holes',()=>{const{d}=seed();d.holes.push({id:'hole',x:23,y:6,drill:3.2,plated:false});d.cutouts.push({id:'cut',points:G.rect(20,14,6,5)});fill(d);assert.deepEqual(bad(d),[]);saveFixture('holes',d);});
test('Stale fills block manufacturing rather than exporting obsolete planes',()=>{const{d}=seed();assert.throws(()=>C.M.files(d),/Refill/);fill(d);P.set(d,'bottom',d.nets[0].id);assert.throws(()=>C.M.files(d),/Refill/);});
test('Thermal settings are persistent and settings changes invalidate the fill',()=>{const{d,n}=seed();fill(d);P.set(d,'bottom',n,{thermal:false,spoke:.8,gap:.4,step:.3});const z=P.get(d,'bottom');assert.equal(z.fill,null);assert.equal(z.thermal,false);assert.equal(C.validateDoc(d).zones[0].spoke,.8);fill(d);assert.equal(P.status(d)[0].connected,1);});
test('Bad trace and via dimensions cannot be used by the connection helper',()=>{for(const change of [d=>d.settings.traceWidth=.01,d=>d.settings.viaDrill=.2,d=>d.settings.viaDiameter=.45]){const{d,p}=linkFixture();change(d);assert.throws(()=>P.planConnections(d,[p.id+':0'],'bottom'));}});
test('Plane export becomes an ordinary zone in the documented KiCad subset',()=>{const{d}=seed();fill(d);const s=C.K.export(d);assert(s.includes('(zone '));const imported=C.K.import(s).document;assert(imported.zones.length);assert(imported.zones.every(z=>!z.boardPlane));assert.equal(P.list(C.validateDoc(d)).length,1);});
test('Power and ground planes remain isolated when a ground attachment pierces both faces',()=>{const{d,n,p}=linkFixture(),v=C.newNet(d,'+5V');pad(d,25,6,v,'top',true);P.set(d,'top',v);const a=P.planConnections(d,[p.id+':0'],'bottom');assert.equal(a.vias.length,1);assert.equal(P.list(a.document).length,2);assert.deepEqual(bad(a.document),[]);assert.equal(a.document.parts.find(x=>x.id===p.id).pads[0].net,n);saveFixture('power-ground',a.document);});
const record={version:C.VERSION,passed:results.filter(r=>r.pass).length,total:results.length,results};fs.writeFileSync(path.join(OUT,'plane-core-results.json'),JSON.stringify(record,null,2));console.log(`${record.passed}/${record.total} plane engine tests passed.`);
