'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
for(const f of ['core','geometry','font','platforms','manufacturing','router','interchange'])require('../src/'+f+'.js');
const C=globalThis.CB,P=C.Platforms,G=C.G,M=C.M,results=[];
const near=(a,b)=>assert(Math.abs(a-b)<.00015,`${a} != ${b}`);
function test(name,fn){try{fn();results.push({name,pass:true});console.log('PASS '+name);}catch(e){results.push({name,pass:false,error:e.stack});console.error('FAIL '+name,e.stack);process.exitCode=1;}}
const only=d=>d.parts[0],pads=d=>C.pads(d),get=(d,pin)=>pads(d).find(p=>p.pin===String(pin));
function holes(d){return G.holes(d).filter(h=>!h.plated);}
function coordSet(a){return a.map(p=>[C.q(p.x),C.q(p.y),p.drill]).sort((a,b)=>a[0]-b[0]||a[1]-b[1]);}
test('All six mating variants exist and their contact IDs are unique',()=>{assert.equal(C.LIB.filter(f=>f.category==='Platforms').length,6);for(const f of C.LIB.filter(f=>f.platform)){assert.equal(new Set(f.pads.map(p=>p.number)).size,f.pads.length);assert(f.pads.every(p=>p.signal&&p.drill===1));assert.equal(f.verified,false);}});
test('Pi 40-pin HAT template uses top-view physical pin 1, GPIO aliases, and four mounts',()=>{const d=P.template('pi40');assert.equal(only(d).side,'bottom');assert.equal(d.board.width,65);assert.equal(d.board.height,56);near(get(d,1).x,8.37);near(get(d,1).y,4.77);near(get(d,2).y,2.23);near(get(d,40).x,56.63);assert.equal(get(d,1).signal,'3V3');assert.equal(get(d,3).signal,'GPIO2 / SDA1');assert.equal(get(d,27).pinType,'reserved');assert.equal(get(d,28).signal,'ID_SC / GPIO1');assert.equal(holes(d).length,4);near(G.dist(holes(d)[0],holes(d)[1]),58);});
test('Uno R3 preserves the exact 4.064 mm D8–D7 discontinuity',()=>{const d=P.template('uno-r3');const a=get(d,'DIGITAL10.10'),b=get(d,'DIGITAL8.1');near(b.x-a.x,4.064);near(a.y,2.54);near(get(d,'POWER.1').x,27.94);near(get(d,'ANALOG.6').x,63.5);near(get(d,'POWER.1').y,50.8);assert.equal(get(d,'POWER.1').signal,'NC');assert.equal(get(d,'DIGITAL8.8').signal,'D0 / RX');assert.equal(pads(d).length,32);});
test('MKR 28-pin contact mapping and 20.32 mm row separation are preserved',()=>{const d=P.template('mkr',{role:'addon'});assert.equal(pads(d).length,28);near(get(d,1).x,21.92);near(get(d,1).y,22.76);near(get(d,28).x,21.92);near(get(d,1).y-get(d,28).y,20.32);near(get(d,2).x-get(d,1).x,2.54);assert.equal(get(d,1).signal,'AREF');assert.equal(get(d,14).signal,'D5');assert.equal(get(d,15).signal,'D6');assert.equal(get(d,28).signal,'5V');assert.equal(get(d,21).signal,'D12 / SCL');});
test('Add-on and carrier mating variants share the same top-view pattern, not a double mirror',()=>{for(const f of P.families){const a=P.template(f.id,{role:'addon',margin:0}),b=P.template(f.id,{role:'carrier',margin:0});assert.equal(only(a).side,'bottom');assert.equal(only(b).side,'top');assert.deepEqual(pads(a).map(p=>[p.pin,p.x,p.y]),pads(b).map(p=>[p.pin,p.x,p.y]));assert.deepEqual(coordSet(holes(a)),coordSet(holes(b)));}});
test('All template variants pass geometry DRC but retain explicit review warnings',()=>{for(const f of P.families)for(const role of ['addon','carrier']){const d=P.template(f.id,{role});assert.deepEqual(G.findings(d).filter(f=>f.severity==='error'),[]);assert(G.findings(d).some(f=>f.code==='platform-review'));assert.equal(d.nets.length,0);assert(pads(d).every(p=>p.net===null));assert(only(d).locked);}});
test('Schema 1 is migrated; new schema 2 files are not accepted by a v1.0-only reader',()=>{const d=C.example();d.schema=1;d.version='1.0.0';const migrated=C.validateDoc(d);assert.equal(migrated.schema,2);assert.equal(migrated.version,C.VERSION);assert.equal(d.schema,1);assert.equal(P.template('pi40').schema,2);});
test('Native JSON preserves embedded pin aliases, mounting holes, and display options',()=>{const a=P.template('mkr',{role:'carrier'});only(a).platform.showHost=false;const b=C.validateDoc(JSON.parse(JSON.stringify(a)));assert.deepEqual(a,b);assert.deepEqual(P.pinCSV(only(a)),P.pinCSV(only(b)));});
test('Legacy v1.0 documents load without inventing platform data',()=>{const d=C.validateDoc(JSON.parse(fs.readFileSync(path.join(__dirname,'../examples/starter.json'),'utf8')));assert(d.parts.length>0);assert(d.parts.every(p=>!p.platform));assert.equal(C.mountingHoles(d).length,0);});
test('Rotation and flipping move mounting holes with their interface',()=>{const d=P.template('uno-r3'),p=only(d),before=holes(d),c={x:p.x,y:p.y};p.rotation=90;holes(d).forEach((h,i)=>{near(h.x,c.x-(before[i].y-c.y));near(h.y,c.y+(before[i].x-c.x));});p.rotation=0;p.side='top';holes(d).forEach((h,i)=>{near(h.x,2*c.x-before[i].x);near(h.y,before[i].y);});});
test('Resizing the board does not stretch connector geometry or mounting holes',()=>{const d=P.template('uno-r3'),a=pads(d).map(p=>[p.x,p.y,p.drill]),b=coordSet(holes(d));d.board.width+=20;d.board.height+=10;assert.deepEqual(a,pads(d).map(p=>[p.x,p.y,p.drill]));assert.deepEqual(b,coordSet(holes(d)));});
test('Header-only placement does not drill unrequested host mounting holes',()=>{const d=C.blank();d.parts.push(C.makePart(d,'platform-pi40-addon',32.5,28));assert.equal(C.mountingHoles(d).length,0);assert(!Object.keys(M.files(d)).some(n=>n.includes('NPTH')));});
test('Reference visibility never changes Gerber or drill bytes',()=>{for(const f of P.families){const d=P.template(f.id),a=M.files(d);only(d).platform.showHost=false;only(d).platform.showPins=false;assert.deepEqual(M.files(d),a);}});
test('Manufacturing exports exactly the interface drills, not host circuitry',()=>{for(const f of P.families){const d=P.template(f.id),out=M.files(d);assert.equal(M.readDrill(out['board-PTH.drl']).objects.length,f.pads.length);assert.equal(M.readDrill(out['board-NPTH.drl']).objects.length,4);const cu=M.readGerber(out['board-F_Cu.gbr']).objects;assert.equal(cu.length,f.pads.length);assert(cu.every(o=>o.kind==='flash'));}});
test('Mounting holes stay aligned in top/bottom copper and explicit-decimal Excellon',()=>{const d=P.template('mkr',{role:'carrier'}),p=only(d);p.rotation=35;p.side='bottom';d.board.width=120;d.board.height=100;p.x=60;p.y=50;const out=M.files(d),a=M.readDrill(out['board-NPTH.drl']).objects.map(o=>({x:o.a.x,y:d.board.height-o.a.y,drill:o.diameter}));assert.deepEqual(coordSet(a),coordSet(holes(d)));assert.deepEqual(M.readGerber(out['board-F_Cu.gbr']).objects,M.readGerber(out['board-B_Cu.gbr']).objects);});
test('KiCad subset keeps every connector contact and NPTH coordinate after transforms',()=>{for(const f of P.families){const d=P.template(f.id,{role:'carrier'}),p=only(d);p.rotation=90;p.side='bottom';p.x=70;p.y=65;d.board.width=140;d.board.height=140;const k=C.K.import(C.K.export(d)).document;assert.deepEqual(pads(d).map(p=>[p.pin,p.x,p.y,p.drill]),pads(k).map(p=>[p.pin,p.x,p.y,p.drill]));assert.deepEqual(coordSet(holes(d)),coordSet(holes(k)));}});
test('Removing optional mounts changes only NPTH-related outputs, not copper',()=>{const d=P.template('pi40'),before=M.files(d);P.setHoles(only(d),false);const after=M.files(d);assert(!after['board-NPTH.drl']);assert.equal(before['board-F_Cu.gbr'],after['board-F_Cu.gbr']);assert.equal(before['board-Edge_Cuts.gbr'],after['board-Edge_Cuts.gbr']);assert.equal(only(d).verified,false);});
test('Mounting holes enter route obstacles and copper-to-NPTH checks',()=>{const d=P.template('pi40'),h=holes(d)[0],net=C.newNet(d,'TEST');d.traces.push({id:'test-trace',net,layer:'top',width:.4,points:[{x:h.x,y:h.y},{x:h.x+2,y:h.y}]});assert(G.findings(d).some(f=>f.code==='hole-copper'));assert(G.obstacles(d,net,'top').items.some(i=>i.kind==='hole'));});
test('Selected-pin router can attach a new test point to a named Pi GPIO',()=>{const d=P.template('pi40'),p=get(d,11),q=C.makePart(d,'testpoint',p.x,16);d.parts.push(q);const n=C.newNet(d,'GPIO17');C.assignPads(d,[p.id,q.id+':0'],n);const r=C.R.routeGroup(d,[p.id,q.id+':0']);assert.equal(r.failures.length,0);d.traces.push(...r.traces);d.vias.push(...r.vias);assert.equal(G.connectivity(d).unrouted,0);});
test('Unknown metadata versions and malformed mounting coordinates are rejected',()=>{for(const mutate of [p=>p.platform.schema=99,p=>p.platform.outline[0].x=Infinity,p=>p.mountingHoles[0].drill=-1,p=>p.platform.holePattern='bad',p=>p.pads[0].signal={html:'bad'}]){const d=P.template('pi40');mutate(only(d));assert.throws(()=>C.validateDoc(d));}});
test('Library-based duplication creates independent metadata and unassigned nets',()=>{const d=C.blank(),a=C.makePart(d,'platform-mkr-carrier',35,25);d.parts.push(a);const b=C.makePart(d,'platform-mkr-carrier',35,65);a.platform.showHost=false;P.setHoles(a,true);assert.equal(b.platform.showHost,true);assert.equal(b.mountingHoles.length,0);assert.notEqual(a.ref,b.ref);assert(b.pads.every(p=>p.net===null));});
test('Pin-map CSV records physical IDs and signals without creating project nets',()=>{const d=P.template('uno-r3'),csv=P.pinCSV(only(d));assert(csv.includes('"POWER.1","NC"'));assert(csv.includes('"DIGITAL8.8","D0 / RX"'));assert.equal(csv.trim().split('\r\n').length,33);assert.equal(d.nets.length,0);});
test('NC-contact review is surfaced without silently removing its user assignment',()=>{const d=P.template('uno-r3'),p=get(d,'POWER.1');const n=C.newNet(d,'CHECK');C.assignPads(d,[p.id],n);assert(G.findings(d).some(f=>f.code==='platform-nc'));assert.equal(get(d,'POWER.1').net,n);});
const output=path.join(__dirname,'output');fs.mkdirSync(output,{recursive:true});fs.writeFileSync(path.join(output,'platform-results.json'),JSON.stringify({version:C.VERSION,date:new Date().toISOString(),passed:results.filter(r=>r.pass).length,total:results.length,results},null,2));
// Generated outputs for the independent Python manufacturing regression.
for(const family of P.families)for(const role of ['addon','carrier']){const d=P.template(family.id,{role}),dir=path.join(output,'fixtures','platforms',family.id+'-'+role);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'project.json'),JSON.stringify(d,null,2));for(const [name,text] of Object.entries(M.files(d)))fs.writeFileSync(path.join(dir,name),text);}
console.log(`${results.filter(r=>r.pass).length}/${results.length} platform tests passed.`);
