'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
for(const f of ['core','geometry','vias','font','platforms','manufacturing','router','planes','interchange'])require('../src/'+f+'.js');
const C=globalThis.CB,G=C.G,M=C.M,OUT=path.join(__dirname,'output'),FIX=path.join(OUT,'fixtures','silkscreen');fs.mkdirSync(FIX,{recursive:true});const results=[];
function test(name,fn){try{fn();results.push({name,pass:true});console.log('PASS',name);}catch(e){results.push({name,pass:false,error:e.message});console.error('FAIL',name,e.stack);process.exitCode=1;}}
function board(){let d=C.blank();d.board={...d.board,width:80,height:55,shape:'rect'};return d;}
function part(d,id,x=25,y=25){const p=C.makePart(d,id,x,y);d.parts.push(p);return p;}
function fixture(name,d){const dir=path.join(FIX,name);fs.mkdirSync(dir,{recursive:true});fs.writeFileSync(path.join(dir,'project.json'),JSON.stringify(d,null,2));for(const [n,t] of Object.entries(M.files(d)))fs.writeFileSync(path.join(dir,n),t);fs.writeFileSync(path.join(dir,'source-strokes.json'),JSON.stringify(C.silkStrokes(d)));fs.writeFileSync(path.join(dir,'source-shapes.json'),JSON.stringify(C.silkRects(d)));}
function near(a,b){assert(Math.abs(a-b)<.0002,`${a} != ${b}`);}
// Point-compositing oracle: a region's contours are UNIONED (Gerber 4.10).
function inkAt(text,p){let ink=false;for(const o of M.readGerber(text).objects){let covers=false;if(o.kind==='region')covers=o.contours.some(c=>G.inside(p,c));else if(o.kind==='line')covers=G.pointSegDist(p,o.a,o.b)<=o.width/2;else if(o.kind==='flash')covers=o.shape==='C'?Math.hypot(p.x-o.x,p.y-o.y)<=o.sizes[0]/2:Math.abs(p.x-o.x)<=o.sizes[0]/2&&Math.abs(p.y-o.y)<=o.sizes[1]/2;if(covers)ink=o.polarity!=='clear';}return ink;}
// G.pointSegDist's actual exported name is pseg; use an independent elementary formula.
G.pointSegDist=(p,a,b)=>{let dx=b.x-a.x,dy=b.y-a.y,len=dx*dx+dy*dy,t=len?Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/len)):0;return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy);};
function line(d,layer='top'){d.art.push({id:C.uid('ink'),kind:'line',points:[{x:0,y:0},{x:10,y:0}],x:30,y:10,rotation:0,width:.5,layer,mirror:false});}
test('Diodes and LEDs explicitly identify both anode and cathode',()=>{for(const id of ['diode','led5']){const d=board(),p=part(d,id);assert.deepEqual(p.pads.map(a=>C.polarityRole(p,a)),['cathode','anode']);assert.deepEqual(C.pads(d).map(a=>a.polarityLabel),['Cathode','Anode']);}});
test('Polarized capacitors use positive/negative roles, not diode voltage assumptions',()=>{const d=board(),p=part(d,'cap-radial');assert.deepEqual(C.polarityMarks(p).map(a=>[a.short,a.label]),[['+','Positive'],['-','Negative']]);});
test('Legacy A/K and +/- built-ins gain labels without changing geometry or net IDs',()=>{for(const id of ['diode','led5','cap-radial']){const d=board(),p=part(d,id),n=C.newNet(d,'GND');p.pads[0].net=n;p.pads.forEach(a=>delete a.polarity);const before=JSON.stringify(d);assert.equal(C.polarityMarks(p).length,2);M.files(d);assert.equal(JSON.stringify(d),before);}});
test('No numeric or net-name polarity inference for imported/custom connectors',()=>{const d=board(),p=part(d,'header2'),n=C.newNet(d,'ANODE');p.pads[0].net=n;p.pads[0].signal='K';p.pads[0].number='+';assert.equal(C.polarityMarks(p).length,0);p.body.kind='diode';assert.equal(C.polarityMarks(p).length,0);});
test('User-defined roles work without changing numeric pin identities or nets',()=>{const d=board(),p=part(d,'header2'),before=p.pads.map(a=>a.number);p.pads[0].polarity='anode';p.pads[1].polarity='cathode';assert.deepEqual(C.polarityMarks(p).map(a=>a.label),['Anode','Cathode']);assert.deepEqual(p.pads.map(a=>a.number),before);assert(p.pads.every(a=>a.net===null));});
test('Explicit none suppresses a legacy role instead of re-inferring it',()=>{const d=board(),p=part(d,'diode');p.pads[0].polarity='none';assert.equal(C.polarityMarks(p).length,1);});
test('Silkscreen polarity is independent of reference-label visibility',()=>{const d=board(),p=part(d,'led5');p.label.visible=false;assert(C.silkStrokes(d).length>0);p.polaritySilk={visible:false};assert.equal(C.silkStrokes(d).length,0);assert.equal(C.polarityMarks(p).length,2);});
test('Printed polarity stays on the component face, including flipped through-hole parts',()=>{const d=board(),p=part(d,'led5');p.label.visible=false;p.side='bottom';assert(C.silkStrokes(d).every(s=>s.layer==='bottom'));assert(M.silkInventory(d).find(s=>s.layer==='bottom').strokes>0);assert.equal(M.silkInventory(d).find(s=>s.layer==='top').strokes,0);});
test('Polarity anchors preserve physical pin identity through flips and arbitrary rotation',()=>{const d=board(),p=part(d,'diode');for(const side of ['top','bottom'])for(const rotation of [0,37,90,180,270]){p.side=side;p.rotation=rotation;const marks=C.polarityMarks(p);for(const m of marks){const a=p.pads[m.index],r=rotation*Math.PI/180,x=a.x*(side==='bottom'?-1:1);near(m.pad.x,p.x+x*Math.cos(r)-a.y*Math.sin(r));near(m.pad.y,p.y+x*Math.sin(r)+a.y*Math.cos(r));assert.equal(m.role,a.polarity);}}});
test('Default printed marks clear their own body and mask openings',()=>{for(const id of ['diode','led5','cap-radial']){const d=board(),p=part(d,id);p.label.visible=false;assert(!G.findings(d).some(f=>['silk-mask','silk-edge'].includes(f.code)));}});
test('Polarity size, gap and offsets survive native schema-3 JSON',()=>{const d=board(),p=part(d,'diode');p.polaritySilk={visible:true,size:2,gap:1.1,x:.5,y:-2};const copy=C.validateDoc(d);assert.equal(copy.schema,3);assert.deepEqual(copy.parts[0].polaritySilk,p.polaritySilk);assert.deepEqual(C.polarityMarks(copy.parts[0]),C.polarityMarks(p));});
test('Invalid roles and polarity marking dimensions are rejected on import',()=>{for(const f of [p=>p.pads[0].polarity='magic',p=>p.polaritySilk={visible:'yes'},p=>p.polaritySilk={size:-1},p=>p.polaritySilk={gap:0},p=>p.polaritySilk={x:200}]){const d=board(),p=part(d,'led5');f(p);assert.throws(()=>C.validateDoc(d));}});
test('An on-board drawn line survives the entire exported top silkscreen stack',()=>{const d=board();line(d);assert(inkAt(M.files(d)['board-F_Silkscreen.gbr'],{x:35,y:45}));fixture('simple-line',d);});
test('On-board bottom artwork survives clipping without mirroring board coordinates',()=>{const d=board();line(d,'bottom');assert(inkAt(M.files(d)['board-B_Silkscreen.gbr'],{x:25,y:45}));assert(!inkAt(M.files(d)['board-F_Silkscreen.gbr'],{x:25,y:45}));});
test('Old nested-clear-frame reproducer has NO ink under standard Gerber semantics',()=>{const d=board(),w=new M.GerberWriter(d,'Legend,Top');w.line([{x:10,y:10},{x:30,y:10}],.5);w.polarityTo('clear');w.region([G.rect(-1,-1,82,57),G.outline(d)]);const t=w.finish();assert(!inkAt(t,{x:20,y:45}));fs.writeFileSync(path.join(FIX,'legacy-frame.gbr'),t);});
test('Overlapping dark contours are unioned even when winding directions oppose',()=>{const d=board(),w=new M.GerberWriter(d,'Legend,Top');w.region([G.rect(4,4,40,30),G.rect(10,10,10,10).reverse()]);assert(inkAt(w.finish(),{x:15,y:40}));fs.writeFileSync(path.join(FIX,'union-contours.gbr'),w.finish());});
test('Every exported clipping region has one closed contour',()=>{const d=C.example('mixed');for(const [n,t] of Object.entries(M.files(d)).filter(([n])=>n.includes('Silkscreen')))for(const o of M.readGerber(t).objects.filter(o=>o.kind==='region'))assert.equal(o.contours.length,1,n);});
test('Nested-frame fix retains physical holes and pad-mask clipping',()=>{const d=board();d.art.push({id:'solid',kind:'image',x:-10,y:-10,rotation:0,layer:'top',rects:[{x:0,y:0,w:100,h:80}]});const p=part(d,'header2',20,20);p.label.visible=false;d.holes.push({id:'hole',x:40,y:20,drill:3,slot:0,plated:false});const text=M.files(d)['board-F_Silkscreen.gbr'];assert(inkAt(text,{x:8,y:47}));assert(!inkAt(text,{x:18.73,y:35}));assert(!inkAt(text,{x:40,y:35}));assert(!inkAt(text,{x:-5,y:35}));});
test('Cutout clears only its opening, not all surrounding artwork',()=>{const d=board();d.art.push({id:'solid',kind:'image',x:10,y:10,rotation:0,layer:'top',rects:[{x:0,y:0,w:40,h:30}]});d.cutouts.push({id:'cut',points:G.rect(20,20,8,6)});const text=M.files(d)['board-F_Silkscreen.gbr'];assert(!inkAt(text,{x:24,y:32}));assert(inkAt(text,{x:30,y:32}));});
test('X2 and RS-274X compatibility exports contain identical retained artwork',()=>{const d=C.example('mixed');const a=M.files(d),b=M.files(d,{x2:false});for(const n of Object.keys(a).filter(n=>n.includes('Silkscreen')))assert.deepEqual(M.readGerber(a[n]).objects,M.readGerber(b[n]).objects);});
test('Export is deterministic and never mutates the project',()=>{const d=C.example(),before=JSON.stringify(d),a=M.files(d),b=M.files(d);assert.deepEqual(a,b);assert.equal(JSON.stringify(d),before);});
test('KiCad exchange includes the printable polarity strokes',()=>{const d=board(),p=part(d,'led5');p.label.visible=false;const text=C.K.export(d);assert(text.includes('F.SilkS'));const d2=C.K.import(text).document;assert(C.silkStrokes(d2).length>=C.silkStrokes(d).length);});
test('Gerber reader rejects open contours instead of accepting malformed regions',()=>{assert.throws(()=>M.readGerber('%FSLAX46Y46*%\n%MOMM*%\nG36*\nX0Y0D02*\nX1000000Y0D01*\nX1000000Y1000000D01*\nG37*\nM02*'));});
// Fully flood each face, including far-off-board source artwork; the independent
// Python oracle expects exactly the substrate minus explicit holes/mask openings.
for(const shape of ['rect','rounded','circle','concave','reversed','offset'])test('Exterior clipping fixture: '+shape,()=>{
 const d=board();d.title='Clip proof '+shape;
 if(['rect','rounded','circle'].includes(shape)){d.board.shape=shape;d.board.radius=7;}else{d.board.shape='polygon';d.board.points=shape==='offset'?G.rect(-5,-3,70,48):[{x:0,y:0},{x:80,y:0},{x:80,y:15},{x:45,y:15},{x:45,y:40},{x:80,y:40},{x:80,y:55},{x:0,y:55}];if(shape==='reversed')d.board.points.reverse();}
 for(const layer of ['top','bottom'])d.art.push({id:C.uid('flood'),kind:'image',layer,x:layer==='top'?-250:250,y:-200,rotation:0,rects:[{x:0,y:0,w:500,h:450}]});
 d.cutouts.push({id:'cut',points:G.rect(22,22,5,6)});d.holes.push({id:'hole',x:10,y:10,drill:3,slot:0,rotation:0,plated:false},{id:'slot',x:35,y:10,drill:1.2,slot:4,rotation:30,plated:false});
 const p=part(d,'header2',12,30);p.label.visible=false;const n=C.newNet(d,'GND');d.vias.push({id:'open-via',x:30,y:40,diameter:1,drill:.4,net:n,tented:false},{id:'tented-via',x:36,y:40,diameter:1,drill:.4,net:n,tented:true});
 const smd=part(d,'R0805',30,16);smd.side='bottom';smd.label.visible=false;
 fixture('clip-'+shape,d);const text=M.files(d)['board-F_Silkscreen.gbr'];assert(inkAt(text,{x:5,y:35}));assert(!inkAt(text,{x:-200,y:20}));
});
test('Text, references, images and all supported drawing tools have export fixtures',()=>{
 const d=board();d.title='Polarity and silkscreen proof';for(const [i,id]of ['diode','led5','cap-radial'].entries())part(d,id,17+i*23,22);
 const b=part(d,'led5',55,40);b.side='bottom';b.rotation=37;
 d.art.push({id:'title',kind:'text',text:'POLARITY & SILK',size:2.3,width:.25,x:11,y:5,rotation:0,layer:'top'}, {id:'bottom-title',kind:'text',text:'BOTTOM INK',size:1.8,width:.25,x:63,y:7,rotation:0,layer:'bottom'},
 {id:'line',kind:'line',x:8,y:12,points:[{x:0,y:0},{x:64,y:0}],width:.25,layer:'top'},
 {id:'rect',kind:'rect',x:10,y:33,w:8,h:7,width:.25,layer:'top'}, {id:'circle',kind:'circle',x:22,y:33,w:8,h:7,width:.25,layer:'top'},
 {id:'poly',kind:'poly',x:35,y:33,points:[{x:0,y:0},{x:6,y:0},{x:3,y:6}],closed:true,width:.25,layer:'top'},
 {id:'filled',kind:'poly',x:46,y:34,points:[{x:0,y:0},{x:6,y:0},{x:3,y:6}],closed:true,filled:true,width:.25,layer:'top'},
 {id:'image',kind:'image',x:60,y:34,rotation:0,layer:'top',rects:[{x:0,y:0,w:1,h:6},{x:1,y:0,w:5,h:1},{x:1,y:2.5,w:3,h:1},{x:1,y:5,w:5,h:1}]});
 fixture('all-tools',d);assert(M.silkInventory(d).every(s=>s.strokes>0));
});
fs.writeFileSync(path.join(OUT,'silkscreen-results.json'),JSON.stringify({passed:results.filter(r=>r.pass).length,total:results.length,results},null,2));console.log(`${results.filter(r=>r.pass).length}/${results.length} tests passed.`);
