'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
for(const f of ['core','geometry','vias','font','platforms','manufacturing','router','interchange'])require('../src/'+f+'.js');
const C=globalThis.CB,G=C.G,V=C.V,M=C.M,results=[];
function test(name,fn){try{fn();results.push({name,pass:true});console.log('PASS '+name);}catch(e){results.push({name,pass:false,error:e.message});console.error('FAIL '+name,e);process.exitCode=1;}}
function board(){const d=C.blank();d.title='Via validation fixture';d.board={...d.board,width:40,height:30,shape:'rect'};return d;}
function trace(d,n,side='top',y=10){const t={id:C.uid('t'),net:n,layer:side,width:.4,points:[{x:5,y},{x:35,y}],locked:false};d.traces.push(t);return t;}
function pair(){const d=board(),n=C.newNet(d,'LINK');for(const [x,side] of [[8,'top'],[32,'bottom']]){const p=C.makePart(d,'testpoint',x,10);p.pads[0].drill=0;p.pads[0].net=n;p.side=side;p.verified=true;p.label.visible=false;d.parts.push(p);}d.traces=[{id:'top-trace',net:n,layer:'top',width:.4,points:[{x:8,y:10},{x:20,y:10}]},{id:'bottom-trace',net:n,layer:'bottom',width:.4,points:[{x:20,y:10},{x:32,y:10}]}];return{d,n};}
const point={x:20,y:10};
test('Via defaults are present and native JSON uses the current schema',()=>{const d=board();assert.equal(d.schema,C.SCHEMA);assert.deepEqual(V.defaults(d),{diameter:.9,drill:.4,tented:false});});
test('All size presets pass the bundled profile',()=>{for(const p of V.presets)assert(V.sizeCheck(board(),p).ok);});
test('Invalid and undersized diameters are rejected before placement',()=>{for(const s of [{diameter:NaN,drill:.4},{diameter:.3,drill:.4},{diameter:.4,drill:.4},{diameter:.9,drill:.2},{diameter:.5,drill:.4},{diameter:30,drill:1}])assert(!V.sizeCheck(board(),s).ok);});
test('Project-specific ring and drill constraints govern proposals',()=>{const d=board();d.profile.minDrill=.5;assert(!V.propose(d,point).ok);d.settings.viaDrill=.5;d.profile.minRing=.3;assert(!V.propose(d,point).ok);d.settings.viaDiameter=1.2;assert(V.propose(d,point).ok);});
test('Preview is pure and does not add via, net, or artwork',()=>{const d=board(),before=JSON.stringify(d);assert(V.propose(d,point).ok);assert.equal(JSON.stringify(d),before);});
test('An empty-space via can be explicitly unassigned and is flagged by checks',()=>{const d=board();V.add(d,point,{net:null});assert.equal(d.vias.length,1);assert.equal(d.holes.length,0);assert(G.findings(d).some(f=>f.code==='unassigned-via'));});
test('Auto net inherits top copper without adding a new electrical net',()=>{const d=board(),n=C.newNet(d,'GND');trace(d,n);const v=V.add(d,point);assert.equal(v.net,n);assert.equal(d.nets.length,1);});
test('Auto net can inherit bottom copper',()=>{const d=board(),n=C.newNet(d,'GND');trace(d,n,'bottom');assert.equal(V.add(d,point).net,n);});
test('A via cannot silently bridge different top and bottom nets',()=>{const d=board(),a=C.newNet(d,'A'),b=C.newNet(d,'B');trace(d,a);trace(d,b,'bottom');const before=JSON.stringify(d);assert.equal(V.propose(d,point).code,'via-net-conflict');assert.throws(()=>V.add(d,point));assert.equal(JSON.stringify(d),before);});
test('Explicit net assignment still checks the opposite layer',()=>{const d=board(),a=C.newNet(d,'A'),b=C.newNet(d,'B');trace(d,b,'bottom');assert(!V.propose(d,point,{net:a}).ok);});
test('Unassigned copper is not silently treated as one shared net',()=>{const d=board();trace(d,null);assert(!V.propose(d,point,{net:null}).ok);assert(!V.propose(d,point).ok);});
test('Unknown net IDs stop creation without modifying the board',()=>{const d=board(),before=JSON.stringify(d);assert.throws(()=>V.add(d,point,{net:'missing'}));assert.equal(JSON.stringify(d),before);});
test('Outer edges and internal cutouts protect via copper',()=>{const d=board();assert(!V.propose(d,{x:.2,y:10}).ok);assert(!V.propose(d,{x:-2,y:10}).ok);d.cutouts.push({id:'cut',points:G.rect(18,8,4,4)});assert(!V.propose(d,point).ok);});
test('Keepouts on either copper face reject a via',()=>{for(const layer of ['top','bottom','both']){const d=board();d.keepouts.push({id:'keep',layer,points:G.rect(18,8,4,4)});assert(!V.propose(d,point).ok);}});
test('Non-plated holes and same-net plated drills enforce spacing',()=>{const d=board();d.holes.push({id:'mount',x:20,y:10,drill:3.2,plated:false});assert(!V.propose(d,point).ok);const b=board(),n=C.newNet(b,'LINK'),p=C.makePart(b,'testpoint',20,10);p.pads[0].net=n;p.pads[0].drill=.8;b.parts.push(p);assert.equal(V.propose(b,point,{net:n}).code,'via-hole-spacing');});
test('Duplicate drill at an existing via is rejected',()=>{const d=board(),n=C.newNet(d,'LINK');V.add(d,point,{net:n});assert.equal(V.propose(d,point,{net:n}).code,'via-hole-spacing');});
test('A single through via joins actual front and back trace geometry',()=>{const{d,n}=pair();assert.equal(G.connectivity(d).unrouted,1);V.add(d,point,{net:n});assert.equal(G.connectivity(d).unrouted,0);assert.equal(G.findings(d).filter(f=>f.severity==='error').length,0);});
test('Moving or deleting the via exposes the lost interlayer connection',()=>{const{d,n}=pair(),v=V.add(d,point,{net:n});V.edit(d,v.id,{y:18});assert.equal(G.connectivity(d).unrouted,1);V.edit(d,v.id,{y:10});assert.equal(G.connectivity(d).unrouted,0);d.vias=[];assert.equal(G.connectivity(d).unrouted,1);});
test('Invalid via edits are rejected atomically; locks protect geometry',()=>{const d=board(),v=V.add(d,point),before=JSON.stringify(v);assert.throws(()=>V.edit(d,v.id,{drill:2}));assert.equal(JSON.stringify(v),before);V.edit(d,v.id,{locked:true});assert.throws(()=>V.edit(d,v.id,{x:22}));V.edit(d,v.id,{locked:false});V.edit(d,v.id,{diameter:1.2});assert.equal(v.diameter,1.2);});
test('Native JSON round-trip preserves sizes, net, tenting, lock, position and defaults',()=>{const d=board(),n=C.newNet(d,'GND');d.settings.viaTented=true;V.add(d,point,{net:n,locked:true});assert.deepEqual(C.validateDoc(JSON.parse(JSON.stringify(d))),d);});
test('Earlier schema-2 projects without a tenting default load safely',()=>{const d=board();delete d.settings.viaTented;assert.equal(C.validateDoc(d).settings.viaTented,false);});
test('Both copper Gerbers contain the same via center and diameter',()=>{const d=board();V.add(d,{x:12.3,y:7.4},{net:C.newNet(d,'LINK'),diameter:1.2,drill:.6});const f=M.files(d),a=M.readGerber(f['board-F_Cu.gbr']).objects,b=M.readGerber(f['board-B_Cu.gbr']).objects;assert.deepEqual(a,b);assert.equal(a.length,1);assert.equal(a[0].x,12.3);assert.equal(a[0].y,22.6);assert.equal(a[0].sizes[0],1.2);});
test('Via emits one plated Excellon drill and no mounting-hole drill',()=>{const d=board();V.add(d,point,{net:C.newNet(d,'LINK')});const f=M.files(d);assert(!f['board-NPTH.drl']);const holes=M.readDrill(f['board-PTH.drl']).objects;assert.equal(holes.length,1);assert.equal(holes[0].diameter,.4);assert.deepEqual(holes[0].a,{x:20,y:20});});
test('Tenting changes mask openings on both sides without changing copper/drills',()=>{const d=board(),v=V.add(d,point,{net:C.newNet(d,'LINK')}),a=M.files(d);v.tented=true;const b=M.files(d);for(const key of ['board-F_Cu.gbr','board-B_Cu.gbr','board-PTH.drl'])assert.equal(a[key],b[key]);for(const face of ['F','B']){assert.equal(M.readGerber(a[`board-${face}_Mask.gbr`]).objects.length,1);assert.equal(M.readGerber(b[`board-${face}_Mask.gbr`]).objects.length,0);}});
test('Trace snapping uses the actual segment rather than the board snap grid',()=>{const d=board(),t=trace(d,null);assert.deepEqual(V.onTrace(t,{x:12.3,y:10.15}),{x:12.3,y:10,dist:.15000000000000036});});
test('KiCad subset preserves via center, dimensions and net geometry',()=>{const{d,n}=pair();V.add(d,point,{net:n});const out=C.K.import(C.K.export(d)).document;assert.equal(out.vias.length,1);for(const k of ['x','y','diameter','drill'])assert.equal(out.vias[0][k],d.vias[0][k]);assert.equal(C.netName(out,out.vias[0].net),'LINK');assert.equal(G.connectivity(out).unrouted,0);});
test('KiCad imports explicitly report open-mask and lock simplification',()=>{const d=board();V.add(d,point,{net:C.newNet(d,'LINK'),tented:true});const result=C.K.import(C.K.export(d));assert.equal(result.document.vias[0].tented,false);assert(result.report.some(x=>x.includes('tenting')&&x.includes('open masks')));});
const out=path.join(__dirname,'output');fs.mkdirSync(out,{recursive:true});
for(const tented of [false,true]){const d=board(),n=C.newNet(d,'VIA_TEST');V.add(d,{x:12.3,y:7.4},{net:n,diameter:1.2,drill:.6,tented});const dir=path.join(out,'fixtures','vias',tented?'tented':'open');fs.mkdirSync(dir,{recursive:true});for(const[name,data]of Object.entries(M.files(d)))fs.writeFileSync(path.join(dir,name),data);fs.writeFileSync(path.join(dir,'project.json'),JSON.stringify(d,null,2));}
const record={version:C.VERSION,date:new Date().toISOString(),passed:results.filter(r=>r.pass).length,total:results.length,results};fs.writeFileSync(path.join(out,'via-results.json'),JSON.stringify(record,null,2));console.log(`${record.passed}/${record.total} via tests passed.`);
