#!/usr/bin/env python3
"""Rebuild checked-in runtime assets without downloading dependencies.

The static source is runnable as shipped. This optional developer command keeps
its embedded worker, portable HTML and content-versioned offline cache in sync.
"""
from __future__ import annotations
import argparse
import base64
import hashlib
import json
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
GENERATED = ("src/worker-source.js", "icon.svg", "manifest.webmanifest", "sw.js", "COPPERBENCH-portable.html")
ICON = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 128 128"><rect width="128" height="128" rx="28" fill="#163e33"/><g fill="none" stroke="#d8a565" stroke-width="7" stroke-linecap="round" stroke-linejoin="round"><path d="M34 24h60v80H34zM17 40h17m-17 24h17m-17 24h17m60-48h17m-17 24h17m-17 24h17"/><path d="M75 44H53v40h22M53 64h19"/></g></svg>'


def generate(root: Path = ROOT) -> dict[str, bytes]:
    """Return generated file bytes; this function does not mutate the tree."""
    def read(name: str) -> str:
        return (root / name).read_text(encoding="utf-8")
    version = json.loads(read("package.json"))["version"]
    worker = "\n;\n".join(read("src/" + name) for name in
                          ("core.js", "geometry.js", "vias.js", "font.js", "platforms.js", "maker-parts.js", "carriers.js", "modules.js", "block-catalog.js", "blocks.js", "router.js", "planes.js", "worker-entry.js"))
    outputs = {
        "src/worker-source.js": "/* Generated by tools/package.py. */\nwindow.CB_WORKER_SOURCE=" + json.dumps(worker, ensure_ascii=True) + ";\n",
        "icon.svg": ICON,
        "manifest.webmanifest": json.dumps({
            "name": "COPPERBENCH — PCB workbench", "short_name": "Copperbench",
            "id": "./", "start_url": "./", "scope": "./", "display": "standalone",
            "background_color": "#f3f1e8", "theme_color": "#163e33",
            "icons": [{"src": "icon.svg", "sizes": "any", "type": "image/svg+xml", "purpose": "any"}]
        }, indent=2) + "\n"
    }
    def asset(name: str) -> str:
        return outputs[name] if name in outputs else read(name)
    index = read("index.html")
    scripts = re.findall(r'<script src="([^"]+)"', index)
    assets = ["./", "index.html", "styles.css", "icon.svg", "manifest.webmanifest", *scripts]
    digest = hashlib.sha256()
    for name in assets[1:]:
        digest.update(name.encode("utf-8") + b"\0" + asset(name).encode("utf-8") + b"\0")
    revision = version + "-" + digest.hexdigest()[:16]
    outputs["sw.js"] = '''/* Generated offline shell. No telemetry or background sync. */
// Cache ownership is scoped: updating one deployment must not clear another.
const PREFIX = 'copperbench:' + self.registration.scope + ':';
const CACHE = PREFIX + REVISION;
const ASSETS = ASSET_LIST;
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(ASSETS)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(
    keys.filter(key => key.startsWith(PREFIX) && key !== CACHE).map(key => caches.delete(key))
  )).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  if (event.request.method !== 'GET' || new URL(event.request.url).origin !== self.location.origin) return;
  event.respondWith(caches.open(CACHE).then(cache => cache.match(event.request))
    .then(hit => hit || fetch(event.request)));
});
'''.replace("REVISION", json.dumps(revision)).replace("ASSET_LIST", json.dumps(assets))
    portable = index.replace('<link rel="manifest" href="manifest.webmanifest">', '')
    portable = portable.replace('href="icon.svg"', 'href="data:image/svg+xml;base64,' + base64.b64encode(ICON.encode()).decode() + '"')
    portable = portable.replace('<link rel="stylesheet" href="styles.css">',
                                '<style>\n' + read('styles.css') + '\n</style><script>window.CB_PORTABLE=true;</script>')
    def inline(match: re.Match) -> str:
        return '<script>\n' + asset(match.group(1)).replace('</script', '<\\/script') + '\n</script>'
    portable = re.sub(r'<script src="([^"]+)"></script>', inline, portable)
    notices = read('LICENSE') + '\n\n' + read('MODULE-NOTICES.txt') + '\n\nJSZip 3.10.1, distributed under its MIT license option:\n' + read('vendor/JSZIP-LICENSE.md').split('GPL version 3')[0]
    portable = portable.replace('<!doctype html>', '<!doctype html>\n<!--\n' + notices.replace('--', '—') + '\n-->')
    outputs['COPPERBENCH-portable.html'] = portable
    return {name: value.encode('utf-8') for name, value in outputs.items()}


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true', help='Fail without writing if generated files are out of date')
    args = parser.parse_args()
    stale = []
    for name, data in generate().items():
        target = ROOT / name
        if not target.is_file() or target.read_bytes() != data:
            stale.append(name)
            if not args.check:
                target.parent.mkdir(parents=True, exist_ok=True)
                target.write_bytes(data)
    if args.check and stale:
        print('Stale generated files: ' + ', '.join(stale))
        print('Run: python3 tools/package.py')
        return 1
    print('Generated assets are current.' if args.check else f'Rebuilt runtime assets ({len(stale)} changed).')
    return 0


if __name__ == '__main__':
    raise SystemExit(main())
