/* COPPERBENCH v1.5 controller interfaces. Original procedural drawings and
 * nominal header geometry transcribed from the references in each record.
 * These are HEADER-MOUNTED carriers/add-ons, not castellated SMT footprints.
 * Copper guards are attached constraints, never decorative copper or silk.
 */
(function(root){'use strict';
const C=root.CB,G=C.G,P=C.Platforms,A=C.Carriers={revision:1};
const pt=(x,y)=>({x:C.q(x),y:C.q(y)});
const pin=(number,signal,x,y,bank)=>({number:String(number),signal,bank,...pt(x,y),w:1.8,h:1.8,drill:1,slot:0,shape:String(number)==='1'||String(number).endsWith('.1')||number==='D0'?'rect':'circle',layers:'both',net:null,pinType:signal==='GND'||signal==='AGND'?'ground':/^(3V3|5V|VBUS|VSYS|VIN|BAT)/.test(signal)?'power':/RESERVED|FREE/.test(signal)?'reserved':'signal'});
const region=(id,name,kind,x,y,w,h)=>({id,name,kind,x,y,w,h});
const common=['Header mounting only: no castellated reflow pads, underside USB/battery/test contacts or debug connector are included.','Nominal 1.0 mm connector drills / 1.8 mm pads are defaults. Check the actual mating connector, assembly tolerance and engagement length.','Pin captions do not join nets. Confirm power direction, voltage and current limits; no supporting power circuitry is inserted.','The host envelope and access areas are 2D references, not a collision-checked mechanical model. Print at 1:1 and verify against the purchased board before ordering.'];
const piSources=['https://www.raspberrypi.com/documentation/microcontrollers/pico-series.html','https://pip.raspberrypi.com/documents/RP-008299-DS'];
const picoSignals=['GP0','GP1','GND','GP2','GP3','GP4','GP5','GND','GP6','GP7','GP8','GP9','GND','GP10','GP11','GP12','GP13','GND','GP14','GP15','GP16','GP17','GND','GP18','GP19','GP20','GP21','GND','GP22','RUN','GP26 / ADC0','GP27 / ADC1','AGND','GP28 / ADC2','ADC_VREF','3V3_OUT','3V3_EN','GND','VSYS','VBUS'];
const defs=[];
for(const [id,title,wireless] of [['pico','Raspberry Pi Pico',false],['pico2','Raspberry Pi Pico 2',false],['pico-w','Raspberry Pi Pico W',true],['pico2-w','Raspberry Pi Pico 2 W',true]]){
 const pads=picoSignals.map((s,i)=>pin(i+1,s,i<20?1.61:19.39,1.37+(i<20?i:39-i)*2.54,i<20?'LEFT':'RIGHT'));
 defs.push({id,title,short:title.replace('Raspberry Pi ','').toUpperCase(),tag:'40-pin · USB at top',width:21,height:51,shape:'rounded',radius:1,pads,holes:[[4.8,2],[16.2,2],[4.8,49],[16.2,49]].map(([x,y])=>({...pt(x,y),drill:2.1})),color:'#39775b',source:piSources,logic:'3.3 V GPIO. Review VBUS, VSYS, 3V3_OUT and 3V3_EN separately; AGND is not silently merged with GND.',note:'Two 20-pin rows, 2.54 mm pitch, 17.78 mm apart. USB-up reference. Header span is centered in the nominal 21 × 51 mm envelope; edge offsets and hole fit require review. '+(wireless?'Wireless host; a suggested under-antenna copper guard is enabled.':'Non-wireless host; no antenna guard.'),review:[...common,'Do not assume SWD/test-pad placement is shared with other Pico variants.',...(wireless?['The editable RF rectangle protects a suggested antenna projection, not a manufacturer-certified antenna exclusion envelope. Review the exact wireless board, nearby metal, enclosure and antenna clearance.']:[])],usbEdge:'top',vertical:true,wireless:wireless?'pcb':'none',regions:[region('usb','USB cable access','access',4.5,-10,12,12),...(wireless?[region('rf','Suggested antenna guard','antenna',6,43,9,15)]:[])]});
}
const nanoLeft=['D13 / SCK','3V3','AREF','A0 / D14','A1 / D15','A2 / D16','A3 / D17','A4 / D18 / SDA','A5 / D19 / SCL','A6 / ADC6','A7 / ADC7','5V','RESET','GND','VIN'];
const nanoRight=['D12 / MISO','D11 / MOSI','D10 / SS','D9','D8','D7','D6','D5','D4','D3','D2','GND','RESET','D0 / RX','D1 / TX'];
defs.push({id:'nano-classic',title:'Arduino Nano · classic A000005',short:'NANO CLASSIC',tag:'30-pin · ATmega328P',width:18,height:43.2,shape:'rect',radius:0,pads:[...nanoRight.map((s,i)=>pin(15-i,s,16.62,3.82+i*2.54,'RIGHT')),...nanoLeft.map((s,i)=>pin(16+i,s,1.38,3.82+i*2.54,'LEFT'))],holes:[[1.38,1.28],[16.62,1.28],[1.38,41.92],[16.62,41.92]].map(([x,y])=>({...pt(x,y),drill:1.8})),color:'#187d83',source:['https://docs.arduino.cc/hardware/nano/','https://docs.arduino.cc/resources/pinouts/A000005-full-pinout.pdf','https://docs.arduino.cc/resources/datasheets/A000005-datasheet.pdf'],logic:'Classic ATmega328P Nano uses 5 V I/O. A6 and A7 are analog inputs, not general digital pins.',note:'Classic Nano only, not Nano Every / 33 / ESP32. 15.24 mm row separation. The 43.2 × 18 mm envelope follows the A000005 mechanical drawing, not a marketing-length claim; verify clones separately.',review:[...common,'Optional 1.8 mm mounting-hole pattern is nominal; verify screw clearance near the end contacts.','ICSP is not included. USB-up orientation; contact 1 is TX at the lower right, contact 16 is D13 at the upper left.'],usbEdge:'top',vertical:true,wireless:'none',regions:[region('usb','Mini-USB cable access','access',3,-11,12,13)]});
const espL=['3V3','EN','GPIO36 / VP / INPUT ONLY','GPIO39 / VN / INPUT ONLY','GPIO34 / INPUT ONLY','GPIO35 / INPUT ONLY','GPIO32','GPIO33','GPIO25','GPIO26','GPIO27','GPIO14','GPIO12 / BOOT STRAP','GND','GPIO13','GPIO9 / FLASH RESERVED','GPIO10 / FLASH RESERVED','GPIO11 / FLASH RESERVED','5V'];
const espR=['GND','GPIO23','GPIO22','GPIO1 / TX','GPIO3 / RX','GPIO21','GND','GPIO19','GPIO18','GPIO5 / BOOT STRAP','GPIO17','GPIO16','GPIO4','GPIO0 / BOOT STRAP','GPIO2 / BOOT STRAP','GPIO15 / BOOT STRAP','GPIO8 / FLASH RESERVED','GPIO7 / FLASH RESERVED','GPIO6 / FLASH RESERVED'];
defs.push({id:'esp32-devkitc-v4',title:'ESP32-DevKitC V4 · WROOM-32E',short:'ESP32 DEVKITC V4',tag:'38-pin · not generic ESP32',width:27.94,height:54.3,shape:'polygon',radius:0,points:[[4.97,0],[22.97,0],[22.97,6.04],[27.94,6.04],[27.94,54.3],[0,54.3],[0,6.04],[4.97,6.04]].map(([x,y])=>pt(x,y)),pads:[...espL.map((s,i)=>pin('J2.'+(i+1),s,1.27,7.31+i*2.54,'J2')),...espR.map((s,i)=>pin('J3.'+(i+1),s,26.67,7.31+i*2.54,'J3'))],holes:[],color:'#303c39',source:['https://docs.espressif.com/projects/esp-dev-kits/en/latest/esp32/esp32-devkitc/user_guide.html','https://dl.espressif.com/dl/schematics/esp32_devkitc_v4_dimensions.pdf','https://docs.espressif.com/projects/esp-hardware-design-guidelines/en/latest/esp32/pcb-layout-design.html'],logic:'3.3 V I/O. Flash contacts are reserved; review input-only and boot-strapping pins. Use the WROOM-32E host, not WROVER or an arbitrary 30/38-pin clone.',note:'19 contacts per bank, 25.4 mm row separation. Reference envelope includes nominal 6.04 mm antenna-module overhang above the 48.26 mm host PCB. USB is at the bottom. No mounting holes.',review:[...common,'Host-edge/header offsets are nominal centered offsets; confirm the exact PCB and module revision.','The suggested RF guard only reserves the antenna projection and extension; apply the full module/manufacturer guidance for nearby copper and metal.','GPIO16/17 use differs on WROVER modules; this template is specifically WROOM-32E.'],usbEdge:'bottom',vertical:true,wireless:'pcb',regions:[region('usb','USB cable access','access',7.97,52.3,12,12),region('rf','Suggested antenna guard','antenna',4.47,-10,19,20)]});
const featherBottom=['RESET','3V3','AREF','GND','A0','A1','A2','A3','A4 / D24','A5 / D25','SCK','MOSI','MISO','RX / D0','TX / D1','FREE / VARIANT SPECIFIC'];
const featherTop=['BAT','EN','VBUS','D13','D12','D11','D10','D9','D6','D5','SCL','SDA'];
defs.push({id:'feather-classic',title:'Adafruit Feather · classic interface',short:'FEATHER / WING',tag:'28-pin · common interface',width:50.8,height:22.86,shape:'rounded',radius:2.54,pads:[...featherBottom.map((s,i)=>pin('L.'+(i+1),s,6.35+i*2.54,21.59,'LOWER')),...featherTop.map((s,i)=>pin('U.'+(i+1),s,16.51+i*2.54,1.27,'UPPER'))],holes:[[2.54,2.54],[48.26,2.54],[2.54,20.32],[48.26,20.32]].map(([x,y])=>({...pt(x,y),drill:2.54})),color:'#293b3a',source:['https://learn.adafruit.com/adafruit-feather/feather-specification'],logic:'Common 3.3 V Feather interface aliases only. MCU GPIO mappings and analog capabilities depend on the actual Feather. FREE must not be assumed to be ground.',note:'Classic 2.0 × 0.9 inch footprint, 16 + 12 contacts, USB-left. Choose add-on for a FeatherWing or carrier to mount a Feather. Not a claim of universal board/circuit compatibility.',review:[...common,'L.1–L.16 and U.1–U.12 are COPPERBENCH bank identifiers, not microcontroller pin numbers.','FREE is explicitly variant-specific. Verify AREF, analog support, power behavior and bus usage on the selected Feather.','Wireless Feathers need their own antenna guard: this common non-RF interface cannot predict every radio placement. Add a copper keepout for the exact host when needed.','Optional corner holes and under-host clearance require a real-board fit check.'],usbEdge:'left',vertical:false,wireless:'variant',regions:[region('usb','USB cable access','access',-10,5.43,12,12),region('battery','Battery plug access','access',5, -8,12,10)]});
const xiaoRP=[26,27,28,29,6,7,0,1,2,4,3],xiaoC3=[2,3,4,5,6,7,21,20,8,9,10];
for(const [id,title,gpios,wireless] of [['xiao-rp2040','Seeed XIAO RP2040 · original',xiaoRP,'none'],['xiao-esp32c3','Seeed XIAO ESP32C3',xiaoC3,'external']]){
 const fn=['A0','A1','A2','A3','SDA','SCL','TX','RX','SCK','MISO','MOSI'],signals=gpios.map((g,i)=>'D'+i+' / GPIO'+g+' / '+fn[i]);
 if(wireless==='external')for(const i of [0,8,9])signals[i]+=' / BOOT STRAP';
 const left=signals.slice(0,7),right=['5V / VBUS','GND','3V3',signals[10],signals[9],signals[8],signals[7]],numbers=['5V','GND','3V3','D10','D9','D8','D7'];
 defs.push({id,title,short:id==='xiao-rp2040'?'XIAO RP2040':'XIAO ESP32C3',tag:'14-pin · header mounted',width:17.8,height:21,shape:'rounded',radius:1,pads:[...left.map((s,i)=>pin('D'+i,s,1.28,2.88+i*2.54,'LEFT')),...right.map((s,i)=>pin(numbers[i],s,16.52,2.88+i*2.54,'RIGHT'))],holes:[],color:'#304138',source:[id==='xiao-rp2040'?'https://wiki.seeedstudio.com/XIAO-RP2040/':'https://wiki.seeedstudio.com/XIAO_ESP32C3_Getting_Started/','https://wiki.seeedstudio.com/PCB_Design_XIAO/'],logic:'3.3 V I/O. 5V/VBUS is not a 5 V GPIO. Pin labels identify this exact variant; review power direction and boot pins.',note:'Original 14-contact host, two 7-way rows on a nominal 15.24 mm span. Centered header offsets in a 17.8 × 21 mm reference envelope require physical review. No mounting holes. Not XIAO Plus or other XIAO variants.',review:[...common,'Contact IDs follow the printed D0–D10 and power labels. USB-up top view; no battery/debug pads on the underside are added.',...(wireless==='external'?['ESP32C3 uses an external antenna. The amber connector-access rectangle is NOT an on-board antenna copper guard; route and position the actual antenna/coax separately.']:[])],usbEdge:'top',vertical:true,wireless,regions:[region('usb','USB-C cable access','access',2.9,-10,12,12),...(wireless==='external'?[region('coax','External antenna / coax access','access',4.9,15,8,12)]:[])]});
}
A.families=defs;for(const f of defs){f.controller=true;P.families.push(f);}
const baseFootprint=P.footprint;
P.footprint=function(id,role='addon'){
 const p=baseFootprint(id,role),f=defs.find(f=>f.id===id);if(!f)return p;
 p.name=f.title+' · '+(role==='carrier'?'Carrier sockets':id==='feather-classic'?'FeatherWing headers':'Add-on headers');
 const sign=role==='addon'?-1:1;
 p.carrier={schema:1,revision:1,model:f.title,source:C.clone(f.source),sourceDate:'2026-09-18',usbEdge:f.usbEdge,vertical:f.vertical,wireless:f.wireless,showClearances:true,enforceAntenna:true,overrideReason:'',stackGap:8.5,regions:f.regions.map(r=>({...r,x:C.q((r.x-f.width/2)*sign-(sign<0?r.w:0)),y:C.q(r.y-f.height/2)}))};
 return p;
};
for(const f of defs)for(const role of ['addon','carrier'])C.LIB.push(P.footprint(f.id,role));
A.regions=part=>(part.carrier?.regions||[]).map(r=>({...r,id:part.id+':guard:'+r.id,partId:part.id,layer:'both',points:G.rect(r.x,r.y,r.w,r.h).map(q=>C.world(part,q)),enforced:r.kind==='antenna'&&part.carrier.enforceAntenna}));
C.keepouts=doc=>[...doc.keepouts,...doc.parts.flatMap(p=>A.regions(p).filter(r=>r.enforced))];
const baseValidate=C.validateDoc;
C.validateDoc=function(input){const d=baseValidate(input);for(const p of d.parts){if(!p.carrier)continue;const t=p.carrier,str=(v,max)=>typeof v==='string'&&v.length<=max,num=(v,min,max)=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max;
 if(!p.platform||t.schema!==1||!str(t.model,120)||!num(t.revision,1,100)||!str(t.sourceDate,30)||!['top','bottom','left'].includes(t.usbEdge)||!['none','pcb','external','variant'].includes(t.wireless))throw Error('Unsupported or invalid controller carrier metadata.');
 for(const k of ['vertical','showClearances','enforceAntenna'])if(typeof t[k]!=='boolean')throw Error('Invalid carrier option.');
 if(!str(t.overrideReason,500)||!num(t.stackGap,0,100)||!Array.isArray(t.source)||t.source.length>12||t.source.some(v=>!str(v,1500)||!/^https:\/\//.test(v)))throw Error('Invalid carrier reference / clearance data.');
 if(!Array.isArray(t.regions)||t.regions.length>32)throw Error('Invalid carrier region collection.');const ids=new Set();for(const r of t.regions){if(!str(r.id,50)||!r.id||ids.has(r.id)||!str(r.name,120)||!['antenna','access'].includes(r.kind)||!num(r.x,-500,500)||!num(r.y,-500,500)||!num(r.w,.1,500)||!num(r.h,.1,500))throw Error('Invalid carrier clearance rectangle.');ids.add(r.id);}
 if(t.regions.some(r=>r.kind==='antenna')&&!t.enforceAntenna&&!t.overrideReason.trim())throw Error('Disabling an antenna guard requires a recorded review reason.');
 }return d;};
const baseTemplate=P.template;P.template=function(id,opts={}){const d=baseTemplate(id,opts),p=d.parts[0];if(p.carrier){d.title=p.carrier.model+(p.platform.role==='carrier'?' carrier starter':' add-on starter');d.assumptions.push({id:C.uid('a'),text:'8.5 mm underside stack gap is an editable planning assumption, not a measured connector specification. RF/access rectangles are suggested 2D references requiring review.',status:'open'});d.evidence.push({id:C.uid('e'),text:'v1.5 controller interface: header pinout and nominal geometry source-referenced; physical fit, electrical function and manufacturing acceptance NOT verified.',source:p.carrier.source.join('\n')});}return C.validateDoc(d);};
const baseFindings=G.findings;
G.findings=function(d){const f=baseFindings(d),add=(severity,code,p,message,evidence,objects=[p.id])=>f.push({id:code+'-'+p.id+'-'+f.length,severity,code,message:p.ref+': '+message,evidence,objects,confidence:'unverified'});
 for(const p of d.parts.filter(p=>p.carrier)){const t=p.carrier,regions=A.regions(p);
 if(regions.some(r=>r.kind==='antenna'))add('warning',t.enforceAntenna?'carrier-rf-review':'carrier-rf-disabled',p,t.enforceAntenna?'review the suggested antenna guard against the exact host and enclosure.':'ANTENNA COPPER GUARD DISABLED: '+t.overrideReason,'The guard is only a suggested 2D projection. It is not RF performance certification.');
 if(t.wireless==='external'||t.wireless==='variant')add('warning','carrier-antenna-location',p,t.wireless==='external'?'external antenna location/coax routing is not modeled.':'exact Feather variant and any antenna location need review.','No automatic RF keepout can be inferred from this interface.');
 for(const a of p.pads)if(a.net&&a.pinType==='reserved')add('warning','carrier-reserved',p,'review assigned reserved / variant-specific contact '+a.number+'.',a.signal,[p.id]);
 const hostFace=p.side;
 const host=p.platform.outline.map(q=>C.world(p,q));
 for(const other of d.parts.filter(o=>o.id!==p.id&&o.side===hostFace)){const poly=G.rect(-other.body.w/2,-other.body.h/2,other.body.w,other.body.h).map(q=>C.world(other,q));
  for(const r of regions)if(G.polyDist(poly,r.points)<C.EPS)add('warning','carrier-access',p,other.ref+' overlaps '+r.name+' in the host-side projection.','Approximate body bounds only; inspect connectors, cables, enclosure and vertical separation.',[p.id,other.id]);
  if(other.body.z>t.stackGap&&G.polyDist(poly,host)<C.EPS)add('warning','carrier-height',p,other.ref+' exceeds the assumed '+t.stackGap+' mm underside stack gap.','Approximate body height '+other.body.z+' mm; not a 3D collision solver.',[p.id,other.id]);
 }
 }return f;};
if(typeof module!=='undefined')module.exports=A;
})(typeof self!=='undefined'?self:globalThis);
