/* Analytic geometry, conservative clearance tests, connectivity, and vector primitives. */
(function(root){'use strict';const C=root.CB,G=C.G={};
G.dist=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y);
G.cross=(a,b,c)=>(b.x-a.x)*(c.y-a.y)-(b.y-a.y)*(c.x-a.x);
G.dot=(a,b)=>a.x*b.x+a.y*b.y;
G.segDist=(p,a,b)=>{const dx=b.x-a.x,dy=b.y-a.y,l=dx*dx+dy*dy,t=l?C.clamp(((p.x-a.x)*dx+(p.y-a.y)*dy)/l,0,1):0;return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy);};
G.segHit=(a,b,c,d)=>{const x1=G.cross(a,b,c),x2=G.cross(a,b,d),x3=G.cross(c,d,a),x4=G.cross(c,d,b);if(((x1>0&&x2<0)||(x1<0&&x2>0))&&((x3>0&&x4<0)||(x3<0&&x4>0)))return true;return Math.min(G.segDist(a,c,d),G.segDist(b,c,d),G.segDist(c,a,b),G.segDist(d,a,b))<1e-7;};
G.segSegDist=(a,b,c,d)=>G.segHit(a,b,c,d)?0:Math.min(G.segDist(a,c,d),G.segDist(b,c,d),G.segDist(c,a,b),G.segDist(d,a,b));
G.inside=(p,poly)=>{let inside=false;for(let i=0,j=poly.length-1;i<poly.length;j=i++){let a=poly[i],b=poly[j];if(G.segDist(p,a,b)<1e-7)return true;if((a.y>p.y)!==(b.y>p.y)&&p.x<(b.x-a.x)*(p.y-a.y)/(b.y-a.y)+a.x)inside=!inside;}return inside;};
G.bounds=pts=>pts.length?pts.reduce((b,p)=>({minX:Math.min(b.minX,p.x),minY:Math.min(b.minY,p.y),maxX:Math.max(b.maxX,p.x),maxY:Math.max(b.maxY,p.y)}),{minX:Infinity,minY:Infinity,maxX:-Infinity,maxY:-Infinity}):{minX:0,minY:0,maxX:0,maxY:0};
G.boxOverlap=(a,b,g=0)=>a.minX<=b.maxX+g&&a.maxX+g>=b.minX&&a.minY<=b.maxY+g&&a.maxY+g>=b.minY;
G.polyDist=(a,b)=>{if(!a.length||!b.length)return Infinity;if(G.inside(a[0],b)||G.inside(b[0],a))return 0;let v=Infinity;for(let i=0;i<a.length;i++)for(let j=0;j<b.length;j++)v=Math.min(v,G.segSegDist(a[i],a[(i+1)%a.length],b[j],b[(j+1)%b.length]));return v;};
G.boundaryDist=(a,b)=>{let best=Infinity;for(let i=0;i<a.length;i++)for(let j=0;j<b.length;j++){let d=G.segSegDist(a[i],a[(i+1)%a.length],b[j],b[(j+1)%b.length]);if(d<1e-8)return 0;if(d<best)best=d;}return best;};
G.pointPolyDist=(p,a)=>G.inside(p,a)?0:Math.min(...a.map((v,i)=>G.segDist(p,v,a[(i+1)%a.length])));
G.segPolyDist=(a,b,p)=>G.inside(a,p)||G.inside(b,p)?0:Math.min(...p.map((v,i)=>G.segSegDist(a,b,v,p[(i+1)%p.length])));
G.area=p=>p.reduce((a,v,i)=>{let w=p[(i+1)%p.length];return a+v.x*w.y-w.x*v.y;},0)/2;
G.simple=poly=>{if(poly.length<3||Math.abs(G.area(poly))<.01)return false;for(let i=0;i<poly.length;i++)for(let j=i+1;j<poly.length;j++){if(j===i+1||(i===0&&j===poly.length-1))continue;if(G.segHit(poly[i],poly[(i+1)%poly.length],poly[j],poly[(j+1)%poly.length]))return false;}return true;};
G.circle=(x,y,r,n=48)=>Array.from({length:n},(_,i)=>({x:x+Math.cos(i/n*Math.PI*2)*r,y:y+Math.sin(i/n*Math.PI*2)*r}));
G.rect=(x,y,w,h)=>[{x,y},{x:x+w,y},{x:x+w,y:y+h},{x,y:y+h}];
G.rotate=(p,a,c={x:0,y:0})=>{let r=a*Math.PI/180,x=p.x-c.x,y=p.y-c.y;return{x:c.x+x*Math.cos(r)-y*Math.sin(r),y:c.y+x*Math.sin(r)+y*Math.cos(r)};};
G.capsule=(a,b,w,n=16)=>{let r=w/2,ang=Math.atan2(b.y-a.y,b.x-a.x),p=[];for(let i=0;i<=n;i++){let t=ang-Math.PI/2+i*Math.PI/n;p.push({x:b.x+Math.cos(t)*r,y:b.y+Math.sin(t)*r});}for(let i=0;i<=n;i++){let t=ang+Math.PI/2+i*Math.PI/n;p.push({x:a.x+Math.cos(t)*r,y:a.y+Math.sin(t)*r});}return p;};
G.roundRect=(x,y,w,h,r)=>{r=Math.max(0,Math.min(r,w/2,h/2));if(!r)return G.rect(x,y,w,h);let p=[];for(const [cx,cy,start] of [[x+w-r,y+r,-90],[x+w-r,y+h-r,0],[x+r,y+h-r,90],[x+r,y+r,180]])for(let i=0;i<=16;i++){let t=(start+i*90/16)*Math.PI/180;p.push({x:C.q(cx+Math.cos(t)*r),y:C.q(cy+Math.sin(t)*r)});}return p;};
G.outline=d=>d.board.shape==='polygon'?d.board.points:d.board.shape==='circle'?Array.from({length:128},(_,i)=>({x:C.q(d.board.width/2+Math.cos(i/128*2*Math.PI)*d.board.width/2),y:C.q(d.board.height/2+Math.sin(i/128*2*Math.PI)*d.board.height/2)})):G.roundRect(0,0,d.board.width,d.board.height,d.board.shape==='rounded'?d.board.radius:0);
G.padPoly=(p,extra=0)=>{let w=p.w+extra*2,h=p.h+extra*2,poly;if(p.shape==='circle')poly=G.circle(0,0,Math.max(w,h)/2,48);else if(p.shape==='oval'){if(w>=h)poly=G.capsule({x:-(w-h)/2,y:0},{x:(w-h)/2,y:0},h);else poly=G.capsule({x:0,y:-(h-w)/2},{x:0,y:(h-w)/2},w);}else poly=G.rect(-w/2,-h/2,w,h);return poly.map(a=>{let t=G.rotate(a,p.rotation||0);return{x:p.x+t.x,y:p.y+t.y}});};
G.holeEndpoints=h=>{let a=(h.rotation||0)*Math.PI/180,l=(h.slot||0)/2;return[{x:h.x-Math.cos(a)*l,y:h.y-Math.sin(a)*l},{x:h.x+Math.cos(a)*l,y:h.y+Math.sin(a)*l}];};
G.holes=d=>[...d.holes.map(h=>({...h,plated:!!h.plated})),...(C.mountingHoles?C.mountingHoles(d):[]),...C.pads(d).filter(p=>p.drill).map(p=>({id:p.id,x:p.x,y:p.y,drill:p.drill,slot:p.slot||0,rotation:p.rotation,plated:true})),...d.vias.map(v=>({...v,plated:true,slot:0,rotation:0}))];
G.safeDisk=(d,p,r=0)=>{let outline=G.outline(d);if(!G.inside(p,outline))return false;for(let i=0;i<outline.length;i++)if(G.segDist(p,outline[i],outline[(i+1)%outline.length])<r-C.EPS/3)return false;for(const cut of d.cutouts){if(G.pointPolyDist(p,cut.points)<r||G.inside(p,cut.points))return false;}return true;};
G.layerMatch=(a,b)=>a===b||a==='both'||b==='both';
G.primitive=(kind,layer,net,owner,poly,extra={})=>({kind,layer,net,owner,poly,box:G.bounds(poly),...extra});
G.copper=function(d,includeZones=true){let out=[];for(const p of C.pads(d))out.push(G.primitive('pad',p.layers,p.net,p.id,G.padPoly(p),{pad:p,partId:p.partId}));for(const v of d.vias)out.push(G.primitive('via','both',v.net,v.id,G.circle(v.x,v.y,v.diameter/2),{via:v}));for(const t of d.traces)for(let i=1;i<t.points.length;i++)out.push(G.primitive('trace',t.layer,t.net,t.id,G.capsule(t.points[i-1],t.points[i],t.width),{a:t.points[i-1],b:t.points[i],width:t.width}));if(includeZones)for(const z of d.zones)for(const r of z.fill?.rects||[])out.push(G.primitive('zone',z.layer,z.net,z.id,G.rect(r.x,r.y,r.w,r.h)));return out;};
class Spatial{constructor(items,size=4){this.size=size;this.map=new Map;this.items=items;items.forEach((x,i)=>this.add(x.box,i));}add(b,id){for(let x=Math.floor(b.minX/this.size);x<=Math.floor(b.maxX/this.size);x++)for(let y=Math.floor(b.minY/this.size);y<=Math.floor(b.maxY/this.size);y++){let k=x+','+y;if(!this.map.has(k))this.map.set(k,[]);this.map.get(k).push(id);}}query(b,gap=0){let ids=new Set;for(let x=Math.floor((b.minX-gap)/this.size);x<=Math.floor((b.maxX+gap)/this.size);x++)for(let y=Math.floor((b.minY-gap)/this.size);y<=Math.floor((b.maxY+gap)/this.size);y++)for(const i of this.map.get(x+','+y)||[])ids.add(i);return [...ids].filter(i=>G.boxOverlap(this.items[i].box,b,gap));}}
G.Spatial=Spatial;
G.obstacles=function(d,net,layer,opts={}){const managed=new Set(d.zones.filter(z=>z.boardPlane).map(z=>z.id));let items=G.copper(d).filter(x=>x.net!==net&&G.layerMatch(x.layer,layer)&&(opts.includeBoardPlanes||!managed.has(x.owner)));for(const h of G.holes(d).filter(h=>!h.plated)){let [a,b]=G.holeEndpoints(h);items.push(G.primitive('hole','both',null,h.id,G.capsule(a,b,h.drill)));}for(const k of C.keepouts(d))if(G.layerMatch(k.layer,layer))items.push(G.primitive('keepout',k.layer,null,k.id,k.points));return{items,index:new Spatial(items)};};
G.pathClear=function(d,points,width,net,layer,obs){obs=obs||G.obstacles(d,net,layer);const r=width/2,clear=d.profile.clearance+C.EPS,outline=G.outline(d);for(let i=1;i<points.length;i++){let a=points[i-1],b=points[i];if(!G.inside(a,outline)||!G.inside(b,outline)||outline.some((p,k)=>G.segSegDist(a,b,p,outline[(k+1)%outline.length])<r+d.profile.edge+C.EPS)||d.cutouts.some(c=>G.segPolyDist(a,b,c.points)<r+d.profile.edge+C.EPS))return{ok:false,reason:'Board edge or cutout clearance'};let box=G.bounds([a,b]);for(const k of obs.index.query(box,r+clear)){let o=obs.items[k];if(G.segPolyDist(a,b,o.poly)<r+clear)return{ok:false,reason:'Blocked by '+o.kind,owner:o.owner};}}return{ok:true};};
G.connectivity=function(d){const items=G.copper(d),parent=items.map((_,i)=>i),find=x=>{while(parent[x]!==x){parent[x]=parent[parent[x]];x=parent[x];}return x},join=(a,b)=>{parent[find(a)]=find(b)},s=new Spatial(items);for(let i=0;i<items.length;i++){let a=items[i];if(!a.net)continue;for(const j of s.query(a.box,C.EPS)){if(j<=i)continue;let b=items[j];if(a.net===b.net&&G.layerMatch(a.layer,b.layer)&&G.polyDist(a.poly,b.poly)<.00001)join(i,j);}}
 const groups={},padGroups={};for(let i=0;i<items.length;i++){let p=items[i];if(p.kind!=='pad'||!p.net)continue;groups[p.net]??={};(groups[p.net][find(i)]??=[]).push(p.pad);padGroups[p.owner]=find(i);}
 const air=[];for(const [net,gs] of Object.entries(groups)){let components=Object.values(gs),connected=components.shift()||[];while(components.length){let best=null;components.forEach((set,k)=>set.forEach(b=>connected.forEach(a=>{let dist=G.dist(a,b);if(!best||dist<best.dist)best={a,b,dist,k};})));air.push({net,a:best.a,b:best.b});connected.push(...components.splice(best.k,1)[0]);}}
 const objectGroups={},zoneGroups={},zoneRoots={};for(let i=0;i<items.length;i++){const a=items[i],key=String(find(i));if(!a.net)continue;const ids=objectGroups[a.owner]??=[];if(!ids.includes(key))ids.push(key);if(a.kind==='zone'){(zoneRoots[a.owner]??=[]).push(key);const zg=zoneGroups[a.owner]??={};zg[key]=(zg[key]||0)+Math.abs(G.area(a.poly));}}
 return{groups,padGroups,air,unrouted:air.length,objectGroups,zoneGroups,zoneRoots};};
G.findings=function(d){const f=[],add=(severity,code,message,objects=[],evidence='',confidence='certain')=>f.push({id:'f'+f.length,severity,code,message,objects,evidence,confidence}),outline=G.outline(d),items=G.copper(d),index=new Spatial(items),p=d.profile;
 if(!G.simple(outline))add('error','outline','Board outline is open, self-intersecting, or has zero area.',['board'],'Outline polygon topology');
 if(d.board.width<p.minWidth||d.board.height<p.minHeight||d.board.width>p.maxWidth||d.board.height>p.maxHeight)add('error','board-size','Board dimensions exceed the selected profile.',['board'],`${d.board.width} × ${d.board.height} mm`);
 for(const cut of d.cutouts){if(!G.simple(cut.points)||cut.points.some(v=>!G.inside(v,outline)))add('error','cutout','Cutout must be a simple closed polygon inside the board.',[cut.id]);let b=G.bounds(cut.points);if(Math.min(b.maxX-b.minX,b.maxY-b.minY)<p.minCutout)add('error','cutout-tool','Cutout is smaller than the profile milling tool.',[cut.id],p.minCutout+' mm tool');}
 const refs=new Set;for(const part of d.parts){if(refs.has(part.ref))add('error','reference','Duplicate component reference '+part.ref,[part.id]);refs.add(part.ref);if(!part.verified)add('warning','footprint','Check '+part.ref+' against its component datasheet.',[part.id],part.source,'unverified');if(!G.inside(part,outline))add('warning','body-outside',part.ref+' body origin is outside the board.',[part.id]);}
 for(const t of d.traces){if(t.width<p.minTrace-C.EPS/10)add('error','trace-width','Trace is narrower than the profile minimum.',[t.id],`${t.width} mm < ${p.minTrace} mm`);if(!t.net)add('error','unassigned-copper','A trace has no electrical net.',[t.id]);}
 for(const v of d.vias){if((v.diameter-v.drill)/2<p.minRing-C.EPS/10)add('error','via-ring','Via annular ring is too small.',[v.id]);if(!v.net)add('error','unassigned-via','A via has no electrical net.',[v.id]);}
 for(const pad of C.pads(d)){if(pad.drill&&(Math.min(pad.w-(pad.slot||0),pad.h)-pad.drill)/2<p.minRing-C.EPS/10)add('error','pad-ring',pad.ref+'.'+pad.pin+' annular ring is too small.',[pad.partId],`Pad ${pad.w} × ${pad.h}; drill ${pad.drill} mm`);if(!pad.net)add('info','unassigned-pin',pad.ref+'.'+pad.pin+' has no assigned net.',[pad.partId]);}
 const holes=G.holes(d);for(let i=0;i<holes.length;i++){const h=holes[i];if(h.drill<p.minDrill-C.EPS/10)add('error','drill','Hole is below the minimum drill diameter.',[h.id],h.drill+' mm');if(h.slot&&h.drill<p.minSlot)add('error','slot','Slot is narrower than the minimum slot width.',[h.id],h.drill+' mm');let [a,b]=G.holeEndpoints(h);if(!G.safeDisk(d,a,h.drill/2)||!G.safeDisk(d,b,h.drill/2)||outline.some((v,i)=>G.segSegDist(a,b,v,outline[(i+1)%outline.length])<h.drill/2-C.EPS)||d.cutouts.some(c=>G.segPolyDist(a,b,c.points)<h.drill/2-C.EPS))add('error','hole-edge','A drill or slot breaks the board edge/cutout.',[h.id]);for(let j=i+1;j<holes.length;j++){let [c,e]=G.holeEndpoints(holes[j]);if(G.segSegDist(a,b,c,e)<(h.drill+holes[j].drill)/2+p.minHoleGap-C.EPS)add('error','hole-spacing','Drill holes overlap or have insufficient separation.',[h.id,holes[j].id]);}}
 const seen=new Set;for(let i=0;i<items.length;i++){const a=items[i];if((a.poly.some(v=>!G.inside(v,outline))||G.boundaryDist(a.poly,outline)<p.edge-C.EPS||d.cutouts.some(c=>G.boxOverlap(a.box,G.bounds(c.points),p.edge)&&G.polyDist(a.poly,c.points)<p.edge-C.EPS))&&!seen.has('edge'+a.owner)){seen.add('edge'+a.owner);add('error','copper-edge','Copper is outside the board or too close to an edge.',[a.owner],p.edge+' mm minimum');}
 for(const j of index.query(a.box,p.clearance+C.EPS)){if(j<=i)continue;const b=items[j];if(a.owner===b.owner||!G.layerMatch(a.layer,b.layer)||(a.net&&a.net===b.net))continue;const key=[a.owner,b.owner].sort().join('|');if(seen.has(key))continue;const gap=G.polyDist(a.poly,b.poly);if(gap<p.clearance-C.EPS/2){seen.add(key);add('error',gap<C.EPS?'short':'clearance',gap<C.EPS?'Copper belonging to different/unassigned nets touches.':'Copper clearance is below the profile minimum.',[a.owner,b.owner],`Measured ${gap.toFixed(4)} mm; required ${p.clearance} mm`);}}
 for(const h of holes.filter(h=>!h.plated)){let [u,v]=G.holeEndpoints(h),poly=G.capsule(u,v,h.drill);if(G.boxOverlap(a.box,G.bounds(poly),p.clearance)&&G.polyDist(a.poly,poly)<p.clearance-C.EPS){const key=a.owner+h.id;if(!seen.has(key)){seen.add(key);add('error','hole-copper','Copper is too close to a non-plated hole.',[a.owner,h.id]);}}}
 for(const k of C.keepouts(d))if(G.layerMatch(a.layer,k.layer)&&G.boxOverlap(a.box,G.bounds(k.points))&&G.polyDist(a.poly,k.points)<C.EPS){let key=a.owner+k.id;if(!seen.has(key)){seen.add(key);add('error','keepout','Copper crosses a keepout.',[a.owner,k.id]);}}
 }
 for(const z of d.zones){if(!z.net)add('error','zone-net','Copper zone needs a net.',[z.id]);if(!z.fill)add('error','zone-stale','Copper zone needs refilling before fabrication.',[z.id]);if(z.fill?.removedIslands)add('info','zone-islands',z.fill.removedIslands+' isolated copper islands removed.',[z.id]);if(z.fill?.rects.length===0)add('warning','zone-empty','Copper zone has no retained copper.',[z.id]);}
 const silk=C.silkStrokes?C.silkStrokes(d):[];for(const a of d.art){if(a.width<p.minSilk-C.EPS/10&&a.kind!=='image')add('warning','silk-width','Silkscreen stroke is below the recommended minimum.',[a.id],a.width+' mm');}
 const masks=C.pads(d).map(x=>({p:x,poly:G.padPoly(x,p.maskExpansion)}));for(const s of silk){let b=G.bounds(s.points),key='silk'+s.owner;if(seen.has(key))continue;if(s.points.some(v=>!G.safeDisk(d,v,s.width/2))) {seen.add(key);add('warning','silk-edge','Silkscreen will be clipped at the board edge.',[s.owner]);continue;}for(const m of masks){if(!G.layerMatch(s.layer,m.p.layers)||!G.boxOverlap(b,G.bounds(m.poly),s.width/2))continue;if(s.points.slice(1).some((v,i)=>G.segPolyDist(s.points[i],v,m.poly)<s.width/2)){seen.add(key);add('warning','silk-mask','Silkscreen overlaps a pad opening and will be clipped.',[s.owner],m.p.ref+'.'+m.p.pin);break;}}}
 for(let i=0;i<masks.length;i++)for(let j=i+1;j<masks.length;j++){let a=masks[i],b=masks[j];if(!G.layerMatch(a.p.layers,b.p.layers)||!G.boxOverlap(G.bounds(a.poly),G.bounds(b.poly),p.minMaskWeb))continue;let gap=G.polyDist(a.poly,b.poly);if(gap>0&&gap<p.minMaskWeb-C.EPS)add('warning','mask-web','A narrow solder-mask web may not survive fabrication.',[a.p.partId,b.p.partId],gap.toFixed(4)+' mm; profile '+p.minMaskWeb+' mm');}
 for(const a of C.silkRects?C.silkRects(d):[]){let key='silk'+a.owner;if(seen.has(key))continue;if(a.poly.some(v=>!G.inside(v,outline))||d.cutouts.some(c=>G.polyDist(a.poly,c.points)<.001)){seen.add(key);add('warning','silk-edge','Silkscreen artwork will be clipped at the board boundary.',[a.owner]);continue;}for(const m of masks)if(G.layerMatch(a.layer,m.p.layers)&&G.boxOverlap(G.bounds(a.poly),G.bounds(m.poly))&&G.polyDist(a.poly,m.poly)<.001){seen.add(key);add('warning','silk-mask','Silkscreen artwork overlaps a pad opening and will be clipped.',[a.owner],m.p.ref+'.'+m.p.pin);break;}}
 const conn=G.connectivity(d);for(const a of conn.air)add('error','unrouted',C.netName(d,a.net)+': '+a.a.ref+'.'+a.a.pin+' is not copper-connected to '+a.b.ref+'.'+a.b.pin,[a.a.partId,a.b.partId],'Connectivity from actual pads, traces, vias, and filled zones');
 if(C.Planes)for(const a of C.Planes.findings(d,conn))add(a.severity,a.code,a.message,a.objects,'Filled copper connectivity; not a current-capacity or circuit-function check');
 return f.sort((a,b)=>({error:0,warning:1,info:2}[a.severity]-{error:0,warning:1,info:2}[b.severity]));
};
if(typeof module!=='undefined')module.exports=G;
})(typeof self!=='undefined'?self:globalThis);
