/* Explicit, bounded KiCad 6+ s-expression subset. Unsupported manufacturing
   geometry is rejected rather than silently discarded. Native JSON is lossless. */
(function(root){'use strict';const C=root.CB,G=C.G,K=C.K={};
const Q=s=>JSON.stringify(String(s??'')),num=v=>C.q(v).toString(),xy=p=>num(p.x)+' '+num(p.y),layer=l=>l==='bottom'?'B':'F';
K.export=function(d){let s=['(kicad_pcb (version 20240108) (generator "copperbench")','  (general (thickness '+num(d.board.thickness)+'))','  (paper "A4")','  (layers (0 "F.Cu" signal) (31 "B.Cu" signal) (34 "B.Paste" user) (35 "F.Paste" user) (36 "B.SilkS" user) (37 "F.SilkS" user) (38 "B.Mask" user) (39 "F.Mask" user) (44 "Edge.Cuts" user) (46 "B.CrtYd" user) (47 "F.CrtYd" user) (48 "B.Fab" user) (49 "F.Fab" user))','  (setup (pad_to_mask_clearance '+num(d.profile.maskExpansion)+') (solder_mask_min_width '+num(d.profile.minMaskWeb)+'))','  (net 0 "")'];let nets=new Map(d.nets.map((n,i)=>[n.id,i+1]));d.nets.forEach(n=>s.push('  (net '+nets.get(n.id)+' '+Q(n.name)+')'));
 const gl=(a,b,w,l)=>s.push(`  (gr_line (start ${xy(a)}) (end ${xy(b)}) (stroke (width ${num(w)}) (type default)) (layer ${Q(l)}))`);
 const poly=(p,l)=>s.push(`  (gr_poly (pts ${p.map(v=>'(xy '+xy(v)+')').join(' ')}) (stroke (width 0) (type default)) (fill solid) (layer ${Q(l)}))`);
 for(const p of d.parts){s.push(`  (footprint ${Q('Copperbench:'+p.name)} (layer "${layer(p.side)}.Cu") (at ${num(p.x)} ${num(p.y)} 0)`, `    (property "Reference" ${Q(p.ref)} (at 0 0) (layer "${layer(p.side)}.Fab") hide (effects (font (size 1 1) (thickness 0.15))))`, `    (property "Value" ${Q(p.value)} (at 0 2) (layer "${layer(p.side)}.Fab") hide (effects (font (size 1 1) (thickness 0.15))))`);
  const shape=G.rect(-p.body.w/2,-p.body.h/2,p.body.w,p.body.h).map(v=>C.world(p,v)).map(v=>({x:v.x-p.x,y:v.y-p.y}));s.push(`    (fp_poly (pts ${shape.map(v=>'(xy '+xy(v)+')').join(' ')}) (stroke (width 0.1) (type default)) (fill none) (layer "${layer(p.side)}.Fab"))`);
  for(const a of C.pads(d).filter(a=>a.partId===p.id)){let drill=a.drill?` (drill ${a.slot?'oval '+num(a.drill+a.slot)+' '+num(a.drill):num(a.drill)})`:'',ls=a.drill?'"*.Cu" "*.Mask"':`"${layer(p.side)}.Cu" "${layer(p.side)}.Paste" "${layer(p.side)}.Mask"`;s.push(`    (pad ${Q(a.pin)} ${a.drill?'thru_hole':'smd'} ${a.shape} (at ${num(a.x-p.x)} ${num(a.y-p.y)} ${num(-a.rotation)}) (size ${num(a.w)} ${num(a.h)})${drill} (layers ${ls})${a.net?' (net '+nets.get(a.net)+' '+Q(C.netName(d,a.net))+')':''})`);}s.push('  )');
 }
 for(const h of G.holes(d).filter(h=>!h.plated)){s.push(`  (footprint "Copperbench:MountingHole" (layer "F.Cu") (at ${num(h.x)} ${num(h.y)}) (pad "" ${h.plated?'thru_hole':'np_thru_hole'} ${h.slot?'oval':'circle'} (at 0 0 ${num(-(h.rotation||0))}) (size ${num(h.drill+(h.slot||0))} ${num(h.drill)}) (drill ${h.slot?'oval '+num(h.drill+h.slot)+' '+num(h.drill):num(h.drill)}) (layers "*.Cu" "*.Mask")))`);}
 for(const t of d.traces)for(let i=1;i<t.points.length;i++)s.push(`  (segment (start ${xy(t.points[i-1])}) (end ${xy(t.points[i])}) (width ${num(t.width)}) (layer "${layer(t.layer)}.Cu") (net ${nets.get(t.net)||0}))`);
 for(const v of d.vias)s.push(`  (via (at ${num(v.x)} ${num(v.y)}) (size ${num(v.diameter)}) (drill ${num(v.drill)}) (layers "F.Cu" "B.Cu") (net ${nets.get(v.net)||0}))`);
 for(const p of [G.outline(d),...d.cutouts.map(c=>c.points)])p.forEach((a,i)=>gl(a,p[(i+1)%p.length],.05,'Edge.Cuts'));
 for(const a of C.silkStrokes(d))for(let i=1;i<a.points.length;i++)gl(a.points[i-1],a.points[i],a.width,layer(a.layer)+'.SilkS');for(const a of C.silkRects(d))poly(a.poly,layer(a.layer)+'.SilkS');
 for(const z of d.zones)s.push(`  (zone (net ${nets.get(z.net)||0}) (net_name ${Q(C.netName(d,z.net))}) (layer "${layer(z.layer)}.Cu") (hatch edge 0.508) (connect_pads ${z.thermal===false?'yes ':''}(clearance ${num(d.profile.clearance)})) (min_thickness ${num(Math.max(.1524,d.profile.minTrace))}) (fill yes (thermal_gap ${num(z.gap||.3)}) (thermal_bridge_width ${num(z.spoke||.5)})) (polygon (pts ${z.points.map(v=>'(xy '+xy(v)+')').join(' ')})))`);
 for(const k of d.keepouts)for(const l of (k.layer==='both'?['top','bottom']:[k.layer]))s.push(`  (zone (net 0) (net_name "") (layer "${layer(l)}.Cu") (hatch edge 0.508) (connect_pads (clearance 0)) (min_thickness 0.25) (keepout (tracks not_allowed) (vias not_allowed) (pads not_allowed) (copperpour not_allowed) (footprints allowed)) (polygon (pts ${k.points.map(v=>'(xy '+xy(v)+')').join(' ')})))`);
 s.push(')');return s.join('\n');};
K.parse=function(text){if(typeof text!=='string'||text.length>20000000)throw Error('KiCad file is too large.');let tokens=text.match(/"(?:\\.|[^"\\])*"|[()]|[^\s()]+/g)||[],i=0,count=0;function read(depth){if(depth>150||++count>2000000)throw Error('KiCad file is too complex.');let t=tokens[i++];if(t==='('){let a=[];while(i<tokens.length&&tokens[i]!==')')a.push(read(depth+1));if(tokens[i++]!==')')throw Error('Unbalanced KiCad file.');return a;}if(t===')'||t===undefined)throw Error('Malformed KiCad expression.');return t[0]==='"'?JSON.parse(t):t;}let result=read(0);if(i!==tokens.length)throw Error('Unexpected trailing KiCad content.');return result;};
const kids=(a,k)=>a.filter(v=>Array.isArray(v)&&v[0]===k),child=(a,k)=>kids(a,k)[0],val=(a,k,fallback)=>child(a,k)?.[1]??fallback,point=(a,k)=>{let p=child(a,k);if(!p||!Number.isFinite(+p[1])||!Number.isFinite(+p[2]))throw Error('Missing '+k+' coordinates.');return{x:+p[1],y:+p[2]};},points=a=>{let p=child(a,'pts');if(!p)throw Error('Missing polygon points.');return kids(p,'xy').map(t=>({x:+t[1],y:+t[2]}));};
K.arcPoints=function(a,m,b){let den=2*(a.x*(m.y-b.y)+m.x*(b.y-a.y)+b.x*(a.y-m.y));if(Math.abs(den)<1e-10)throw Error('Degenerate arc.');let aa=a.x*a.x+a.y*a.y,mm=m.x*m.x+m.y*m.y,bb=b.x*b.x+b.y*b.y,c={x:(aa*(m.y-b.y)+mm*(b.y-a.y)+bb*(a.y-m.y))/den,y:(aa*(b.x-m.x)+mm*(a.x-b.x)+bb*(m.x-a.x))/den},r=G.dist(a,c),t0=Math.atan2(a.y-c.y,a.x-c.x),tm=Math.atan2(m.y-c.y,m.x-c.x),t1=Math.atan2(b.y-c.y,b.x-c.x),tau=Math.PI*2,wrap=t=>(t%tau+tau)%tau,delta=wrap(t1-t0);if(wrap(tm-t0)>delta)delta-=tau;let n=Math.max(8,Math.ceil(Math.abs(delta)*r/.2));if(n>10000)throw Error('Arc exceeds import limits.');return Array.from({length:n+1},(_,i)=>({x:C.q(c.x+r*Math.cos(t0+delta*i/n)),y:C.q(c.y+r*Math.sin(t0+delta*i/n))}));};
K.import=function(text){const tree=K.parse(text),isFoot=tree[0]==='footprint'||tree[0]==='module';if(!isFoot&&tree[0]!=='kicad_pcb')throw Error('Not a supported KiCad board or footprint.');const d=C.blank(),report=[],fail=[],netmap=new Map([['0',null]]),edgeSegments=[];d.title=isFoot?'Imported footprint':'Imported KiCad board';
 if(!isFoot){const cu=child(tree,'layers')?.slice(1).filter(x=>Array.isArray(x)&&String(x[1]).endsWith('.Cu'))||[];if(cu.some(x=>!['F.Cu','B.Cu'].includes(x[1])))throw Error('Only two-copper-layer boards are supported; inner copper layers were found.');for(const n of kids(tree,'net'))if(String(n[1])!=='0')netmap.set(String(n[1]),C.newNet(d,n[2]));let th=+(val(child(tree,'general')||[],'thickness',1.6));d.board.thickness=th;let setup=child(tree,'setup')||[];d.profile.maskExpansion=+val(setup,'pad_to_mask_clearance',d.profile.maskExpansion);}
 const side=l=>{if(!['F.Cu','B.Cu'].includes(l))throw Error('Unsupported copper layer '+l);return l==='F.Cu'?'top':'bottom';};
 function graphic(t,transform=p=>p){let typ=t[0],l=String(val(t,'layer','')),stroke=child(t,'stroke')||[],width=+val(stroke,'width',val(t,'width',.15));if(!l.endsWith('.SilkS')&&l!=='Edge.Cuts'){if(/\.(Mask|Paste)$/.test(l))fail.push('Explicit mask/paste graphics are not supported.');if(l.endsWith('.Cu'))fail.push('Graphical copper '+typ+' must be converted to supported tracks/zones.');return;}if(l==='F.Mask'||l==='B.Mask'||l==='F.Paste'||l==='B.Paste'){fail.push('Explicit mask/paste graphics are not supported.');return;}let ps=[],closed=false;if(typ.endsWith('_line'))ps=[point(t,'start'),point(t,'end')];else if(typ.endsWith('_rect')){let a=point(t,'start'),b=point(t,'end');ps=G.rect(a.x,a.y,b.x-a.x,b.y-a.y);closed=true;}else if(typ.endsWith('_poly')){ps=points(t);closed=true;}else if(typ.endsWith('_circle')){let a=point(t,'center'),b=point(t,'end');ps=G.circle(a.x,a.y,G.dist(a,b),128);closed=true;}else if(typ.endsWith('_arc')){if(!child(t,'mid')){fail.push('Legacy arc representation is unsupported.');return;}ps=K.arcPoints(point(t,'start'),point(t,'mid'),point(t,'end'));report.push('Arcs flattened to polylines at ≤0.2 mm arc steps.');}else if(typ.endsWith('_text')){if(t.includes('hide'))return;let text=typ==='fp_text'?t[2]:t[1];if(l==='Edge.Cuts'){fail.push('Text on Edge.Cuts is unsupported.');return;}let at=point(t,'at'),effects=child(t,'effects')||[],font=child(effects,'font')||[],size=+val(font,'size',1.5),pos=transform(at);if(!/^[\x20-\x7e\n]*$/.test(text)){fail.push('Non-ASCII silkscreen text needs conversion to graphics.');return;}d.art.push({id:C.uid('a'),kind:'text',text,x:pos.x,y:pos.y,rotation:-(+(child(t,'at')?.[3]||0)),size,width:+val(font,'thickness',.18),layer:l[0]==='B'?'bottom':'top',mirror:false});report.push('Imported text uses the built-in drafting alphabet; inspect its size and placement.');return;}else{fail.push('Unsupported manufacturing graphic '+typ);return;}
 ps=ps.map(transform);if(l==='Edge.Cuts'){let all=closed?[...ps,ps[0]]:ps;for(let i=1;i<all.length;i++)edgeSegments.push([all[i-1],all[i]]);}else {if(val(t,'fill','none')==='solid'&&closed){ // filled polygons retained as explicit image-style polygon objects
  d.art.push({id:C.uid('a'),kind:'poly',x:0,y:0,rotation:0,layer:l[0]==='B'?'bottom':'top',width:Math.max(width,.01),points:ps.map(p=>({x:p.x*(l[0]==='B'?-1:1),y:p.y})),closed:true,filled:true});
 }else d.art.push({id:C.uid('a'),kind:'poly',x:0,y:0,rotation:0,layer:l[0]==='B'?'bottom':'top',width,points:ps.map(p=>({x:p.x*(l[0]==='B'?-1:1),y:p.y})),closed,mirror:false});}}
 const fps=isFoot?[tree]:kids(tree,'footprint').concat(kids(tree,'module'));
 for(const ft of fps){const at=child(ft,'at')||['at',0,0,0],angle=-(+at[3]||0),pos={x:+at[1],y:+at[2]},which=side(val(ft,'layer','F.Cu')),flip=which==='bottom'?-1:1,transform=p=>{let q=G.rotate(p,angle);return{x:pos.x+q.x,y:pos.y+q.y};},props=kids(ft,'property'),reference=props.find(p=>p[1]==='Reference')?.[2]||kids(ft,'fp_text').find(p=>p[1]==='reference')?.[2]||'U'+(d.parts.length+1),value=props.find(p=>p[1]==='Value')?.[2]||kids(ft,'fp_text').find(p=>p[1]==='value')?.[2]||ft[1];let pd=[];
 for(const p of kids(ft,'pad')){let typ=p[2],shape=p[3];if(!['thru_hole','np_thru_hole','smd'].includes(typ)||!['circle','rect','oval'].includes(shape)){fail.push('Unsupported pad '+p[1]+' ('+typ+'/'+shape+').');continue;}if(['solder_mask_margin','solder_paste_margin','solder_paste_margin_ratio','remove_unused_layers','roundrect_rratio','primitives'].some(k=>child(p,k))){fail.push('Per-pad mask/paste/custom rules require review in KiCad.');continue;}
 let a=point(p,'at'),size=point(p,'size'),rot=-(+(child(p,'at')?.[3]||0)),dr=child(p,'drill'),drill=dr?(dr[1]==='oval'?Math.min(+dr[2],+dr[3]):+dr[1]):0,slot=dr?.[1]==='oval'?Math.abs(+dr[2]-+dr[3]):0,slotRot=dr?.[1]==='oval'&&+dr[3]>+dr[2]?90:0;
 if(dr&&child(dr,'offset')){fail.push('Offset pad drills are unsupported.');continue;}
 if(typ==='np_thru_hole'){let w=transform(a);d.holes.push({id:C.uid('h'),...w,drill,slot,rotation:rot+slotRot,plated:false});continue;}
 if(slotRot){fail.push('Vertical slotted plated pads require rotating the footprint before import.');continue;}
 let ls=child(p,'layers')||[];if(typ==='smd'&&!ls.includes(which==='top'?'F.Cu':'B.Cu')){fail.push('SMD pad on a different face from its parent footprint.');continue;}
 let ni=val(p,'net','0');if(!netmap.has(String(ni))){const np=child(p,'net');netmap.set(String(ni),C.newNet(d,np?.[2]||'NET_'+ni));}
 pd.push({number:String(p[1]),x:C.q(a.x*flip),y:C.q(a.y),w:size.x,h:size.y,drill,slot,shape,layers:drill?'both':which,rotation:(rot-angle)*flip,net:netmap.get(String(ni))});}
 if(pd.length){let b=G.bounds(pd),part={id:C.uid('p'),name:String(ft[1]),libraryId:'imported',category:'Imported',ref:reference,value,x:pos.x,y:pos.y,rotation:angle,side:which,pads:pd,body:{kind:'ic',w:Math.max(2,b.maxX-b.minX-1),h:Math.max(2,b.maxY-b.minY+1),z:2.5},label:{x:0,y:4,size:1.3,visible:false},verified:false,source:'Imported KiCad footprint; confirm purchased part and pin mapping.',locked:false};d.parts.push(part);}
 for(const t of ft.filter(x=>Array.isArray(x)&&/^fp_/.test(x[0])))graphic(t,transform);if(kids(ft,'model').length)report.push('External 3D model paths are not embedded; a representative body is used.');}
 if(!isFoot)for(const t of tree.filter(Array.isArray)){let typ=t[0];if(typ==='segment'||typ==='arc'){const l=side(val(t,'layer')),ps=typ==='segment'?[point(t,'start'),point(t,'end')]:K.arcPoints(point(t,'start'),point(t,'mid'),point(t,'end'));d.traces.push({id:C.uid('t'),points:ps,layer:l,width:+val(t,'width'),net:netmap.get(String(val(t,'net','0')))||null,locked:t.includes('locked')});if(typ==='arc')report.push('Copper arc converted to a polyline.');}
 else if(typ==='via'){if(t.includes('blind')||t.includes('micro')){fail.push('Only through vias are supported.');continue;}let ls=child(t,'layers');if(!ls||!ls.includes('F.Cu')||!ls.includes('B.Cu')){fail.push('Via layer span is not two-sided.');continue;}d.vias.push({id:C.uid('v'),...point(t,'at'),diameter:+val(t,'size'),drill:+val(t,'drill'),net:netmap.get(String(val(t,'net','0')))||null,tented:false});}
 else if(typ==='zone'){let p=child(t,'polygon');if(!p){fail.push('Zone without an outline polygon.');continue;}let ls=child(t,'layers'),l=ls?'both':side(val(t,'layer','F.Cu'));if(ls&&ls.slice(1).some(s=>!['F.Cu','B.Cu'].includes(s))){fail.push('Zone uses an unsupported layer.');continue;}if(child(t,'keepout'))d.keepouts.push({id:C.uid('k'),points:points(p),layer:l});else {let fill=child(t,'fill')||[];for(const ll of l==='both'?['top','bottom']:[l])d.zones.push({id:C.uid('z'),points:points(p),layer:ll,net:netmap.get(String(val(t,'net','0')))||null,step:.25,gap:+val(fill,'thermal_gap',.3),spoke:+val(fill,'thermal_bridge_width',.5),thermal:!child(t,'connect_pads')?.includes('yes'),fill:null});report.push('Zone fills invalidated; refill and inspect using COPPERBENCH rules.');}}
 else if(/^gr_/.test(typ))graphic(t);else if(['image','embedded_files','teardrop'].includes(typ))fail.push('Unsupported object '+typ+'.');}
 if(fail.length)throw Error('Import stopped to protect manufacturing geometry:\n'+[...new Set(fail)].join('\n'));
 if(isFoot){if(d.art.length)report.push('Standalone footprint placement imports pads and a representative body only. Original footprint artwork is not placed; recreate or import those markings separately.');return{document:d,footprint:d.parts[0]||null,report:[...new Set(report)]};}
 if(!edgeSegments.length)throw Error('A closed Edge.Cuts outline is required.');let loops=[],remaining=edgeSegments.slice();while(remaining.length){let [a,b]=remaining.shift(),loop=[a,b];while(G.dist(loop[loop.length-1],loop[0])>.002){let end=loop[loop.length-1],i=remaining.findIndex(s=>G.dist(s[0],end)<.002||G.dist(s[1],end)<.002);if(i<0)throw Error('Edge.Cuts contains an open contour or discontinuity.');let pair=remaining.splice(i,1)[0];loop.push(G.dist(pair[0],end)<.002?pair[1]:pair[0]);if(loop.length>40000)throw Error('Outline exceeds import limits.');}loop.pop();if(!G.simple(loop))throw Error('Invalid Edge.Cuts contour.');loops.push(loop);}loops.sort((a,b)=>Math.abs(G.area(b))-Math.abs(G.area(a)));let outline=loops.shift(),bounds=G.bounds(outline),dx=bounds.minX,dy=bounds.minY,shift=p=>({x:C.q(p.x-dx),y:C.q(p.y-dy)});d.board.shape='polygon';d.board.points=outline.map(shift);d.board.width=C.q(bounds.maxX-dx);d.board.height=C.q(bounds.maxY-dy);d.cutouts=loops.map(p=>({id:C.uid('cut'),points:p.map(shift)}));for(const p of d.parts){p.x=C.q(p.x-dx);p.y=C.q(p.y-dy);}for(const k of ['traces','zones','keepouts'])for(const a of d[k])a.points=a.points.map(shift);for(const k of ['holes','vias','art'])for(const a of d[k]){a.x=C.q(a.x-dx);a.y=C.q(a.y-dy);}if(d.vias.length)report.push('Through-via geometry and nets are imported, but per-via tenting and placement locks are not preserved by this subset. Imported vias use open masks; inspect and reapply these settings before fabrication.');report.push('Manufacturer profile is the local default, not imported KiCad project rules. Verify before fabrication.');if(fps.length)report.push('Footprint artwork is flattened; inspect markings after moving imported parts.');return{document:C.validateDoc(d),report:[...new Set(report)]};
};
if(typeof module!=='undefined')module.exports=K;
})(typeof self!=='undefined'?self:globalThis);
